#pragma once

#ifndef INCLUDE_CONTAINER_CONTAINER_BOUNDARY_H
#define INCLUDE_CONTAINER_CONTAINER_BOUNDARY_H

enum yai_container_boundary_state {
    YAI_CONTAINER_BOUNDARY_UNKNOWN = 0,
    YAI_CONTAINER_BOUNDARY_OPEN,
    YAI_CONTAINER_BOUNDARY_RESTRICTED,
    YAI_CONTAINER_BOUNDARY_SEALED
};

#endif
