[package]
name = "yai"
version = "0.0.0-newcore"
edition = "2021"

[[bin]]
name = "yai"
path = "src/main.rs"

[dependencies]
replai = { git = "https://github.com/mothx9/replai", rev = "6230713c3c80140e609f836918811835bd847da4" }
signal-hook = "0.3.18"
libc = "0.2"
yai-engine = { path = "../../engine/yai-engine" }
yai-application = { path = "../../application/yai-application" }
yai-host = { path = "../../application/yai-host" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rustls = "0.23"
webpki-roots = "1"
jsonschema = { version = "0.50.0", default-features = false }

[dev-dependencies]
rcgen = "0.13"
