#pragma once

#ifndef INCLUDE_NET_ROUTE_ROUTE_STATE_H
#define INCLUDE_NET_ROUTE_ROUTE_STATE_H

enum yai_net_route_state {
    YAI_NET_ROUTE_STATE_UNKNOWN = 0,
    YAI_NET_ROUTE_STATE_VALID,
    YAI_NET_ROUTE_STATE_STALE,
    YAI_NET_ROUTE_STATE_REPLAYING,
    YAI_NET_ROUTE_STATE_FAILED
};

#endif
