#pragma once

#ifndef INCLUDE_REGISTRY_STATUS_H
#define INCLUDE_REGISTRY_STATUS_H

enum yai_registry_status {
    YAI_REGISTRY_STATUS_UNKNOWN = 0,
    YAI_REGISTRY_STATUS_READY,
    YAI_REGISTRY_STATUS_READONLY,
    YAI_REGISTRY_STATUS_REBUILDING,
    YAI_REGISTRY_STATUS_FAILED
};

#endif
