#pragma once

#ifndef INCLUDE_ACPI_STATUS_H
#define INCLUDE_ACPI_STATUS_H

enum yai_acpi_status {
    YAI_ACPI_STATUS_UNKNOWN = 0,
    YAI_ACPI_STATUS_PRESENT,
    YAI_ACPI_STATUS_ENABLED,
    YAI_ACPI_STATUS_DISABLED,
    YAI_ACPI_STATUS_FAULT
};

#endif
