#pragma once

#ifndef INCLUDE_NET_DISCOVERY_DISCOVERY_STATE_H
#define INCLUDE_NET_DISCOVERY_DISCOVERY_STATE_H

enum yai_net_discovery_state {
    YAI_NET_DISCOVERY_STATE_UNKNOWN = 0,
    YAI_NET_DISCOVERY_STATE_SCANNING,
    YAI_NET_DISCOVERY_STATE_ENROLLING,
    YAI_NET_DISCOVERY_STATE_STABLE
};

#endif
