#pragma once

#ifndef INCLUDE_GOVERNANCE_BUNDLE_STATE_H
#define INCLUDE_GOVERNANCE_BUNDLE_STATE_H

enum yai_bundle_state {
    YAI_BUNDLE_STATE_UNKNOWN = 0,
    YAI_BUNDLE_STATE_OPEN,
    YAI_BUNDLE_STATE_SEALED,
    YAI_BUNDLE_STATE_PUBLISHED,
    YAI_BUNDLE_STATE_RETIRED
};

#endif
