#pragma once

#ifndef INCLUDE_SUPERVISOR_SUPERVISOR_ACTION_H
#define INCLUDE_SUPERVISOR_SUPERVISOR_ACTION_H

enum yai_supervisor_action {
    YAI_SUPERVISOR_ACTION_NONE = 0,
    YAI_SUPERVISOR_ACTION_OBSERVE,
    YAI_SUPERVISOR_ACTION_THROTTLE,
    YAI_SUPERVISOR_ACTION_QUARANTINE,
    YAI_SUPERVISOR_ACTION_REPLAY
};

#endif
