#pragma once

#ifndef INCLUDE_SUPERVISOR_SUPERVISOR_DECISION_H
#define INCLUDE_SUPERVISOR_SUPERVISOR_DECISION_H

enum yai_supervisor_decision {
    YAI_SUPERVISOR_DECISION_NONE = 0,
    YAI_SUPERVISOR_DECISION_ALLOW,
    YAI_SUPERVISOR_DECISION_DENY,
    YAI_SUPERVISOR_DECISION_DEFER,
    YAI_SUPERVISOR_DECISION_REPLAY
};

#endif
