#pragma once

#ifndef INCLUDE_ACPI_EVENTS_SOURCE_H
#define INCLUDE_ACPI_EVENTS_SOURCE_H

enum yai_acpi_event_source {
    YAI_ACPI_EVENT_SOURCE_UNKNOWN = 0,
    YAI_ACPI_EVENT_SOURCE_GPE,
    YAI_ACPI_EVENT_SOURCE_NOTIFY,
    YAI_ACPI_EVENT_SOURCE_THERMAL,
    YAI_ACPI_EVENT_SOURCE_POWER
};

#endif
