#pragma once

#ifndef INCLUDE_CONTAINER_CONTAINER_ADMISSION_H
#define INCLUDE_CONTAINER_CONTAINER_ADMISSION_H

enum yai_container_admission_result {
    YAI_CONTAINER_ADMISSION_UNKNOWN = 0,
    YAI_CONTAINER_ADMISSION_ALLOW,
    YAI_CONTAINER_ADMISSION_DENY,
    YAI_CONTAINER_ADMISSION_DEFER
};

#endif
