import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
const require=createRequire(path.resolve(import.meta.dirname,'../../studio/package.json'));
const {chromium}=require('playwright-core');
const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-gpu']});
const page=await browser.newPage({viewport:{width:1440,height:900}});page.setDefaultTimeout(10000);
const output=process.env.STUDIO_EVIDENCE_DIR??'/tmp/yai-context-tools';await mkdir(output,{recursive:true});
const errors=[];page.on('pageerror',error=>errors.push(String(error)));
const tool=name=>page.locator(`.context-tool[data-tool="${name}"]`);
const draft=()=>page.getByRole('textbox',{name:'Message to the Case'});
const switchCase=async name=>{await page.locator('.titlebar-case').click();await page.getByRole('dialog',{name:'Open Case'}).getByRole('button',{name:new RegExp(name)}).click();await page.locator('.titlebar-case').getByText(name).waitFor();};
try {
 await page.goto(`${process.env.STUDIO_TEST_URL??'http://127.0.0.1:1431'}/?fixture=developer`);
 await page.getByRole('button',{name:'Conversation',exact:true}).click();
 await draft().fill('CASE_A_UNSENT_DRAFT');
 await page.evaluate(()=>window.originalComposer=document.querySelector('[aria-label="Message to the Case"]'));
 await page.getByRole('button',{name:'Float Conversation',exact:true}).click();
 assert.ok(await tool('Conversation').evaluate(element=>element.classList.contains('context-tool-floating')));
 await page.getByRole('button',{name:'Open Inspector tool',exact:true}).click();
 await page.getByRole('button',{name:'Float Inspector',exact:true}).click();
 await page.getByRole('button',{name:'Pin Inspector',exact:true}).click();
 const pinned=await tool('Inspector').locator('[data-inspected-ref]').getAttribute('data-inspected-ref');
 await page.locator('.live-rail button[aria-label="Environment"]').click();
 await page.locator('.environment-files').getByRole('button',{name:'result_access.rs',exact:true}).click();
 await page.locator('.cm-content').waitFor();
 assert.equal(await tool('Inspector').locator('[data-inspected-ref]').getAttribute('data-inspected-ref'),pinned);
 assert.equal(await draft().inputValue(),'CASE_A_UNSENT_DRAFT');
 await page.getByRole('button',{name:'Unpin Inspector',exact:true}).click();
 assert.notEqual(await tool('Inspector').locator('[data-inspected-ref]').getAttribute('data-inspected-ref'),pinned);
 await page.getByRole('button',{name:'Close Inspector tool',exact:true}).click();
 assert.equal(await tool('Inspector').isVisible(),false);
 await page.getByRole('button',{name:'Open Inspector tool',exact:true}).click();
 await page.getByRole('button',{name:'Close Conversation tool',exact:true}).click();
 assert.equal(await tool('Conversation').isVisible(),false);
 await page.getByRole('button',{name:'Open Conversation tool',exact:true}).click();
 assert.equal(await draft().inputValue(),'CASE_A_UNSENT_DRAFT');
 assert.equal(await page.evaluate(()=>window.originalComposer===document.querySelector('[aria-label="Message to the Case"]')),true,'moving/closing remounted composer');
 await page.getByRole('button',{name:'Focus Work Surface',exact:true}).click();
 assert.equal(await tool('Conversation').isVisible(),false);assert.equal(await tool('Inspector').isVisible(),false);
 await page.getByRole('button',{name:'Restore Workbench',exact:true}).click();
 assert.equal(await tool('Conversation').isVisible(),true);assert.equal(await tool('Inspector').isVisible(),true);
 assert.equal(await draft().inputValue(),'CASE_A_UNSENT_DRAFT');
 const before=await tool('Conversation').boundingBox();
 await page.getByRole('button',{name:'Move Conversation',exact:true}).focus();await page.keyboard.press('ArrowLeft');
 assert.equal((await tool('Conversation').boundingBox()).x,before.x-16);
 await page.getByRole('button',{name:'Resize Conversation',exact:true}).focus();await page.keyboard.press('ArrowLeft');
 assert.equal((await tool('Conversation').boundingBox()).width,before.width-16);
 for(const [width,height] of [[1600,960],[1440,900],[1280,800],[1000,650]]) {
  await page.setViewportSize({width,height});
  await page.waitForFunction(()=>[...document.querySelectorAll('.context-tool-floating:not([hidden])')].every(element=>{const r=element.getBoundingClientRect();return r.x>=12&&r.y>=72&&r.right<=innerWidth-12&&r.bottom<=innerHeight-32;}));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.screenshot({path:`${output}/context-${width}x${height}.png`});
 }
 await page.setViewportSize({width:1440,height:900});
 await page.getByRole('button',{name:'Dock Conversation',exact:true}).click();
 assert.equal(await draft().inputValue(),'CASE_A_UNSENT_DRAFT');
 assert.equal(await page.evaluate(()=>window.originalComposer===document.querySelector('[aria-label="Message to the Case"]')),true);
 await switchCase('Contract review');
 assert.equal(await draft().inputValue(),'');
 await draft().fill('CASE_B_UNSENT_DRAFT');
 assert.equal(await tool('Inspector').count(),0,'another Case retained pinned Inspector');
 await switchCase('Runtime qualification');
 assert.equal(await draft().inputValue(),'CASE_A_UNSENT_DRAFT');
 assert.equal(await tool('Inspector').isVisible(),true,'Case-local floating layout not restored');
 await switchCase('Contract review');assert.equal(await draft().inputValue(),'CASE_B_UNSENT_DRAFT');
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',lane:'browser fixture interaction',proof:['same mounted draft across dock/float/close','independent pinned Inspector','keyboard movement and resize','four bounded viewports','Case-local drafts and layout restored without identity leakage']}));
}finally{await browser.close();}
