import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
const require = createRequire(path.resolve(import.meta.dirname, '../../studio/package.json'));
const { chromium } = require('playwright-core');
const baseUrl = process.env.STUDIO_TEST_URL ?? 'http://127.0.0.1:1422';
const browser = await chromium.launch({ executablePath: '/usr/bin/chromium', headless: true, args: ['--no-sandbox','--disable-gpu'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.setDefaultTimeout(8000);
await mkdir('/tmp/yai-studio-reliability', {recursive:true});
const errors = [];
page.on('console', message => { if(message.type() === 'error') errors.push(message.text()); });
page.on('pageerror', error => errors.push(String(error)));
const observations = [];
const record = (name, facts) => { observations.push({name,...facts}); console.log(JSON.stringify(observations.at(-1))); };
let dialogs=0;
page.on('dialog', async d => { dialogs++; await d.accept(); });
const start = async () => { await page.goto(`${baseUrl}/?fixture=developer`); await page.locator('.workbench-kernel').waitFor(); await page.locator('.live-rail button[aria-label="Environment"]').click(); };
const file = name => page.locator('.environment-files').getByRole('button', { name, exact:true });
const tab = name => page.getByRole('tab').filter({ has: page.locator('.surface-tab-title', { hasText: name }) });
const content = () => page.locator('.cm-content');
try {
 await start();
 await file('result_access.rs').dblclick(); await content().waitFor();
 await file('result_reuse.test').dblclick(); await content().waitFor();
 await tab('result_access.rs').click();
 assert.match(await page.locator('.inspector-hero h2').innerText(), /result_access.rs/);
 record('Active tab and Inspector identity', { tab: await page.getByRole('tab',{selected:true}).innerText(), inspector: await page.locator('.inspector-hero h2').innerText() });
 await page.screenshot({ path:'/tmp/yai-studio-reliability/inspector-mismatch.png' });
 await file('result_access.rs').click();
 assert.equal(await tab('result_access.rs').count(), 1);
 record('Reopen pinned material', { sameTitleTabCount: await tab('result_access.rs').count(), titles: await page.getByRole('tab').allTextContents() });
 await page.screenshot({ path:'/tmp/yai-studio-reliability/duplicate-tabs.png' });
 await start(); await file('result_access.rs').click(); await content().waitFor();
 await content().click(); await page.keyboard.press('Control+End'); await page.keyboard.insertText('\nREVIEW_LOCAL_SENTINEL_20260922');
 await page.locator('.dirty-mark').waitFor();
 await file('result_reuse.test').click(); await content().waitFor();
 assert.equal(await page.locator('.dirty-mark').count(), 1);
 record('Dirty preview retained', { dialogs, dirtyTabCount: await page.locator('.dirty-mark').count(), visibleTabs: await page.getByRole('tab').allTextContents() });
 await file('result_access.rs').click(); await content().waitFor();
 record('Hidden dirty buffer recoverable by reopening same file', { containsLocalEdit: (await content().innerText()).includes('REVIEW_LOCAL_SENTINEL_20260922') });
 await content().click(); await page.keyboard.press('Control+f');
 assert.equal(await page.getByRole('dialog').count(), 0);
 assert.equal(await page.locator('.cm-search').count(), 1);
 record('Ctrl+F editor', { workbenchFindDialogs: await page.getByRole('dialog').count(), editorFindPanels: await page.locator('.cm-search').count() });
 await page.keyboard.press('Escape');
 await page.locator('.titlebar-case').click(); await page.getByRole('dialog',{name:'Open Case'}).getByRole('button',{name:/Contract review/}).click();
 await page.locator('.titlebar-case').getByText('Contract review').waitFor();
 await page.locator('.titlebar-case').click(); await page.getByRole('dialog',{name:'Open Case'}).getByRole('button',{name:/Runtime qualification/}).click();
 await page.locator('.live-rail button[aria-label="Environment"]').click(); await file('result_access.rs').click(); await content().waitFor();
 assert.match(await content().innerText(), /REVIEW_LOCAL_SENTINEL_20260922/);
 record('Switch Case with local edits', { dialogs, localEditSurvives: (await content().innerText()).includes('REVIEW_LOCAL_SENTINEL_20260922') });
 await page.keyboard.press('Control+Shift+p');
 const palette = page.getByRole('dialog',{name:'Command Palette'});
 await palette.waitFor();
 for(let i=0;i<100;i++) await page.keyboard.press('Tab');
 assert.equal(await page.evaluate(() => Boolean(document.activeElement?.closest('.workbench-search'))), true);
 record('Modal keyboard focus', { focusStillInsidePalette: await page.evaluate(() => Boolean(document.activeElement?.closest('.workbench-search'))), focusedElement: await page.evaluate(() => document.activeElement?.outerHTML.slice(0,250)) });
 await page.keyboard.press('Escape');
 for(const [width,height] of [[1600,960],[1440,900],[1280,800],[1000,650]]) {
  await page.setViewportSize({width,height});
  await page.locator('.live-rail button[aria-label="Overview"]').click();
  await page.screenshot({path:`/tmp/yai-studio-reliability/overview-${width}x${height}.png`});
  assert.ok(await page.locator('.kernel-status').evaluate(el => el.getBoundingClientRect().bottom <= innerHeight));
  record('Viewport geometry', {width,height,...await page.evaluate(() => {const r = s => {const e=document.querySelector(s); const b=e?.getBoundingClientRect(); return b?{width:b.width,height:b.height,bottom:b.bottom}:null;};return {shell:r('.live-studio'),status:r('.kernel-status'),surface:r('.live-surface'),center:r('.live-center')};})});
 }
 await page.setViewportSize({width:1600,height:960});
 for(const perspective of ['Environment','Knowledge','Memory','Authority','Work','Compute']) {
  await page.locator(`.live-rail button[aria-label="${perspective}"]`).click();
  await page.waitForTimeout(150);
  await page.screenshot({path:`/tmp/yai-studio-reliability/${perspective.toLowerCase()}-1600x960.png`});
 }
 // Instrumented native boundary: verifies lifetime calls, not OS PTY behavior.
 const native = await browser.newPage({viewport:{width:1440,height:900}});
 await native.addInitScript(() => {
   window.calls = []; window.listeners = {}; let next = 0;
   window.__TAURI__ = {core:{invoke:async(command,args) => {
     window.calls.push({command,args});
     if(command === 'terminal_create') return {terminal_id:`terminal:${++next}`,shell:'sh',cwd:'/tmp'};
   }},event:{listen:async(name,handler) => { const listeners = window.listeners[name] ??= new Map(); const id = Symbol(); listeners.set(id,handler); return () => listeners.delete(id); }}};
 });
 await native.goto(`${baseUrl}/?fixture=developer`);
 await native.locator('.xterm').waitFor();
 const initial = await native.locator('.terminal-viewport').getAttribute('data-terminal-id');
 await native.getByRole('button',{name:'Close bottom panel',exact:true}).click();
 await native.keyboard.press('Control+j');
 assert.equal(await native.locator('.terminal-viewport').getAttribute('data-terminal-id'), initial);
 await native.getByRole('button',{name:'Output',exact:true}).click();
 await native.getByRole('button',{name:'Terminal',exact:true}).last().click();
 assert.equal(await native.locator('.terminal-viewport').getAttribute('data-terminal-id'), initial);
 await native.locator('.titlebar-case').click();
 await native.getByRole('dialog',{name:'Open Case'}).getByRole('button',{name:/Contract review/}).click();
 await native.locator('.titlebar-case').getByText('Contract review').waitFor();
 assert.equal(await native.locator('.terminal-viewport').getAttribute('data-terminal-id'), initial);
 assert.equal(await native.evaluate(() => window.calls.filter(call=>call.command==='terminal_dispose_all').length), 0);
 assert.equal(await native.evaluate(() => window.calls.filter(call=>call.command==='terminal_create').length), 1);
 await native.getByRole('button',{name:'Kill active terminal',exact:true}).click();
 await native.locator('#case-tools').waitFor({state:'hidden'});
 await native.keyboard.press('Control+j');
 await native.locator('.xterm').waitFor();
 assert.notEqual(await native.locator('.terminal-viewport').getAttribute('data-terminal-id'), initial);
 record('Terminal lifecycle boundary', {result:'PASS', invariant:'Hide, panel switch and Case switch retain shell; explicit kill removes it; reopen creates one', qualification:'instrumented Tauri bridge, no OS PTY claim'});
 await native.locator('.live-rail button[aria-label="Environment"]').click();
 await native.locator('.environment-files').getByRole('button',{name:'client-notes.md',exact:true}).click();
 await native.locator('.cm-content').fill('NATIVE_UNSAVED_SENTINEL');
 await native.locator('.dirty-mark').waitFor();
 await native.waitForFunction(()=>window.calls.some(call=>call.command==='desktop_set_dirty' && call.args.dirty));
 native.once('dialog', dialog=>dialog.dismiss());
 await native.evaluate(()=>[...window.listeners['yai://window-close-request'].values()].forEach(listener=>listener({payload:null})));
 assert.equal(await native.evaluate(()=>window.calls.filter(call=>call.command==='desktop_close').length),0);
 assert.equal(await native.locator('.cm-content').textContent(),'NATIVE_UNSAVED_SENTINEL');
 native.once('dialog', dialog=>dialog.accept());
 await native.evaluate(()=>[...window.listeners['yai://window-close-request'].values()].forEach(listener=>listener({payload:null})));
 assert.equal(await native.evaluate(()=>window.calls.filter(call=>call.command==='desktop_close').length),1);
 record('Native close guard', {result:'PASS', invariant:'Window-manager close cancels or confirms through the same dirty-buffer guard', qualification:'instrumented Tauri bridge'});
 await native.close();
 assert.deepEqual(errors, []);
 console.log('PASS: root interaction regressions, console clean');
} finally {await writeFile('/tmp/yai-studio-reliability/observations.json',JSON.stringify(observations,null,2));await browser.close();}
