#pragma once

#ifndef INCLUDE_TRANSPORT_ADMISSION_H
#define INCLUDE_TRANSPORT_ADMISSION_H

enum yai_transport_admission_result {
    YAI_TRANSPORT_ADMISSION_UNKNOWN = 0,
    YAI_TRANSPORT_ADMISSION_ALLOW,
    YAI_TRANSPORT_ADMISSION_DENY,
    YAI_TRANSPORT_ADMISSION_DEFER
};

#endif
