/** UI consumption evidence, keyed by the existing Application operation IDs.
 * This is not an operation registry or authorization decision. Unknown/new IDs stay unqualified. */
export interface StudioOperationPosture { state: "integrated" | "alternative" | "debt"; detail: string; proof?: string }
export const studioOperationPostures: Readonly<Record<string, StudioOperationPosture>> = {
  "case.resume": { state: "integrated", detail: "Explicit operator-stopped checkpoint continuation, retained identity and total budgets; lost ACK observation, exact retry and stale/hidden refusal", proof: "tests/studio/effect-actions.mjs" },
  "cognitive.realization.prepare": { state: "integrated", detail: "Compute selects a retained Turn and inspects the current exact plan without inference; text-positive, incompatible audio, stale and hidden refusals qualified. Multimedia success remains unqualified.", proof: "tests/studio/conversation-actions.mjs" },
  "cognitive.realize": { state: "integrated", detail: "Explicit confirmed text realization retains the exact plan before submission; lost ACK observation and exact retry preserve one dispatch/result. Hidden observation and withdrawn trust refuse.", proof: "tests/studio/conversation-actions.mjs" },
  "cognitive.compose": { state: "integrated", detail: "Explicit execution of a retained text Turn using disclosed canonical part identities; stale/hidden refusal and lost-ACK exact retry without duplicate Turn or dispatch. Subset selection and multimedia prerequisites remain debt.", proof: "tests/studio/conversation-actions.mjs" },
  "conversation.send": { state: "integrated", detail: "Committed text SEND, exact lost-ack retry, canonical result observation and reconnect recovery", proof: "tests/studio/conversation-actions.mjs" },
  "effect.propose": { state: "integrated", detail: "Explicit retained Conversation result to owner-normalized filesystem/process Operation; historical candidate, prose refusal and lost-ACK exact recovery qualified.", proof: "tests/studio/conversation-actions.mjs" },
  "effect.submit": { state: "integrated", detail: "Explicit confirmed canonical file write/process suspension; stale/hidden refusal, required Review, lost ACK and exact retry without repeated effect. Other process actions are not yet UI-qualified.", proof: "tests/studio/conversation-actions.mjs" },
  "effect.reconcile": { state: "integrated", detail: "Explicit observation-only or opted-in filesystem no-effect recovery; stale dialog, hidden/wrong reference and lost-ACK exact receipt tests. Process reconciliation remains observation-only in the owner and lacks a dedicated UI scenario.", proof: "tests/studio/effect-actions.mjs" },
  "provider.suitability.record": { state: "integrated", detail: "Explicit operator-attested conversation suitability, independently from measured qualification", proof: "tests/studio/conversation-actions.mjs" },
  "source.resume": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "source.acquire": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "resource.request": { state: "integrated", detail: "Exact Resource submission and explicit reviewed-request continuation after Host restart; stale confirmation and lost-ACK retry retain one receipt without redispatch.", proof: "tests/studio/resource-setup.mjs" },
  "resource.attach_process": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "knowledge.navigation": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "knowledge.resolve": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "knowledge.search": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "knowledge.inspect": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "execution.list": { state: "integrated", detail: "Work and Executions discover bounded current authorized references, merge exact window references and inspect one selected execution. Restart recovery and Case/Participant isolation are qualified; this is not a complete ledger or dispatch permission.", proof: "tests/studio/execution-discovery.mjs" },
  "execution.get": { state: "integrated", detail: "Exact Source/runtime/Resource observation; cognitive plans and historical Decision to current controlled-effect receipts also qualified by conversation-actions.mjs and effect-actions.mjs. Resource process exit/output and revocation also qualified by resource-setup.mjs. Reads never redispatch.", proof: "tests/studio/execution-actions.mjs" },
  "case.stop": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "case.run": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "application.capabilities": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/kernel.test.cjs" },
  "case.cancel": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.capabilities": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/source-policy-actions.mjs" },
  "case.close": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.create": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.list": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.open": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.summary": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/operational-live.mjs" },
  "decision.frontier.prepare": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "decision.request.prepare": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "decision.trajectory.corpus": { state: "integrated", detail: "Bounded authored historical Decision list; current disclosure, omissions and exact identities", proof: "tests/studio/effect-actions.mjs" },
  "decision.trajectory.evaluate": { state: "integrated", detail: "Authored structural reconstruction coverage; not model quality or authority", proof: "tests/studio/effect-actions.mjs" },
  "decision.trajectory.inspect": { state: "integrated", detail: "Exact historical Decision, pre-cut, basis, qualified consequences and missingness; refused reads clear prior disclosure", proof: "tests/studio/effect-actions.mjs" },
  "events.heartbeat": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/attachment-lifecycle.mjs" },
  "events.subscribe": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/operational-live.mjs" },
  "handoff.accept": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.decline": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.offer": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.reconcile": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.result.record": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "identity.bootstrap": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "identity.current": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "material.read": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/material-lifecycle.mjs" },
  "participant.principal.link": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "participant.role.add": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "participant.view.admit": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "policy.case.bind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-actions.mjs" },
  "policy.case.replace": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-actions.mjs" },
  "policy.case.unbind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-actions.mjs" },
  "policy.ingest": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.publish": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.retire": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.revoke": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.validate": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "provider.case.bind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "provider.qualify": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "provider.inventory": { state: "integrated", detail: "Tenant Providers inventory and unbound-target Inspector; Case bindings remain separate", proof: "tests/studio/compute-actions.mjs" },
  "provider.models": { state: "integrated", detail: "Explicit bounded model discovery during target setup", proof: "tests/studio/conversation-actions.mjs" },
  "provider.register": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "provider.trust.set": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "review.approve": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "review.defer": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "review.deny": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "semantic.recall": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "semantic.fast_search.prepare": { state: "integrated", detail: "Working State inspects exact owner-derived navigation, bounded omissions and unavailable producer without scoring or implicit paging.", proof: "tests/studio/memory-actions.mjs" },
  "semantic.working_state.compile": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "semantic.working_state.page": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "semantic.working_state.refresh": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "source.declare": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/environment-actions.mjs" },
  "source.publish": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/source-policy-actions.mjs" },
  "source.revoke": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/environment-actions.mjs" },
  "tenant.get": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "tenant.list": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "workflow.bind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "workflow.define": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "workflow.input.record": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "workflow.patch.adopt": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "workflow.patch.propose": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "case.recent": { state: "alternative", detail: "Start Center uses the authorized Case list; a separate recency section is not selected." },
  "cognitive.binding.set": { state: "integrated", detail: "Assign/replace an exact primary conversation target from authorized suitability evidence", proof: "tests/studio/conversation-actions.mjs" },
  "cognitive.plan": { state: "debt", detail: "Requires an exact integrity-qualified capability requirement. Studio does not fabricate owner digests; requirement preparation remains unconnected." },
  "events.resume": { state: "alternative", detail: "Host reconnection requests an authoritative snapshot; no claim that missed events were delivered." },
  "resource.import": { state: "integrated", detail: "Authored filesystem/discovery, SQLite query, HTTP, MCP catalog and exact-digest process-runner bindings; YAI resolves native identity, exact retry does not duplicate attachments.", proof: "tests/studio/resource-setup.mjs" },
  "resource.attach": { state: "debt", detail: "Requires a native LocalAccessBinding/carrier plus access contract; authored secure Resource setup is not yet connected." },
  "runtime.readiness": { state: "alternative", detail: "Host telemetry reports actual scheduler supervision; runtime readiness is distinct from application health." },
  "semantic.ambient_refresh.assess": { state: "debt", detail: "Requires a real Conversation/Workflow consumer lineage. Generic inspection is not an ambient consumer." },
  "system.status": { state: "alternative", detail: "Desktop Host telemetry supplies current process/readiness facts; no duplicate status page." },
  "tenant.member.add": { state: "debt", detail: "Requires another enrolled exact Principal. Principal enrollment/discovery and multi-Principal interaction qualification remain open." },
};
export const studioOperationPosture = (id: string): StudioOperationPosture => studioOperationPostures[id] ?? { state: "debt", detail: "New Host operation: awaiting published-contract reconciliation and interaction qualification." };
