/** UI consumption evidence, keyed by the existing Application operation IDs.
 * This is not an operation registry or authorization decision. Unknown/new IDs stay unqualified. */
export interface StudioOperationPosture { state: "integrated" | "alternative" | "debt"; detail: string; proof?: string }
export const studioOperationPostures: Readonly<Record<string, StudioOperationPosture>> = {
  "case.resume": { state: "debt", detail: "Application supports exact queued-work continuation; Studio still needs checkpoint selection and resume/refusal interaction evidence." },
  "cognitive.realization.prepare": { state: "debt", detail: "Application prepares an exact plan from retained Turn parts; authored selection and inspection remain unconnected." },
  "cognitive.realize": { state: "debt", detail: "Reconnect-safe exact-plan submission is available; Studio must retain the plan reference and observe instead of redispatching." },
  "cognitive.compose": { state: "debt", detail: "Application admits one explicit composition intent; source-part and prerequisite selection need an authored interaction." },
  "conversation.send": { state: "integrated", detail: "Committed text SEND, exact lost-ack retry, canonical result observation and reconnect recovery", proof: "tests/studio/conversation-actions.mjs" },
  "effect.propose": { state: "debt", detail: "Exact retained candidate normalization is available; Studio must not construct an authoritative Operation or imply permission." },
  "effect.submit": { state: "debt", detail: "Exact canonical filesystem/process Operation submission is available; review, PREPARE and uncertain-outcome UI need qualification." },
  "effect.reconcile": { state: "debt", detail: "Explicit domain-qualified reconciliation is available; Studio must distinguish observation from permitted no-effect recovery." },
  "provider.suitability.record": { state: "integrated", detail: "Explicit operator-attested conversation suitability, independently from measured qualification", proof: "tests/studio/conversation-actions.mjs" },
  "source.resume": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "source.acquire": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "resource.request": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "resource.attach_process": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "knowledge.navigation": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "knowledge.resolve": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "knowledge.search": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "knowledge.inspect": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "execution.get": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/execution-actions.mjs" },
  "case.stop": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "case.run": { state: "integrated", detail: "Authored exact submission/observation or qualified query", proof: "tests/studio/effect-actions.mjs" },
  "application.capabilities": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/kernel.test.cjs" },
  "case.cancel": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.capabilities": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/source-policy-actions.mjs" },
  "case.close": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.create": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.list": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.open": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "case.summary": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/operational-live.mjs" },
  "decision.frontier.prepare": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "decision.request.prepare": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "decision.trajectory.corpus": { state: "integrated", detail: "Bounded authored historical Decision list; current disclosure, omissions and exact identities", proof: "tests/studio/effect-actions.mjs" },
  "decision.trajectory.evaluate": { state: "integrated", detail: "Authored structural reconstruction coverage; not model quality or authority", proof: "tests/studio/effect-actions.mjs" },
  "decision.trajectory.inspect": { state: "integrated", detail: "Exact historical Decision, pre-cut, basis, qualified consequences and missingness; refused reads clear prior disclosure", proof: "tests/studio/effect-actions.mjs" },
  "events.heartbeat": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/attachment-lifecycle.mjs" },
  "events.subscribe": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/operational-live.mjs" },
  "handoff.accept": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.decline": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.offer": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.reconcile": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "handoff.result.record": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "identity.bootstrap": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "identity.current": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "material.read": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/material-lifecycle.mjs" },
  "participant.principal.link": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "participant.role.add": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "participant.view.admit": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "policy.case.bind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-actions.mjs" },
  "policy.case.replace": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-actions.mjs" },
  "policy.case.unbind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-actions.mjs" },
  "policy.ingest": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.publish": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.retire": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.revoke": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "policy.validate": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/policy-intake.mjs" },
  "provider.case.bind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "provider.qualify": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "provider.inventory": { state: "integrated", detail: "Tenant Providers inventory and unbound-target Inspector; Case bindings remain separate", proof: "tests/studio/compute-actions.mjs" },
  "provider.models": { state: "integrated", detail: "Explicit bounded model discovery during target setup", proof: "tests/studio/conversation-actions.mjs" },
  "provider.register": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "provider.trust.set": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/compute-actions.mjs" },
  "review.approve": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "review.defer": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "review.deny": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "semantic.recall": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "semantic.fast_search.prepare": { state: "debt", detail: "Exact navigation preparation is Application-ready; Conversation tools expose only the SEND policy and truthful fallback, not a direct W-bound inspection interaction." },
  "semantic.working_state.compile": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "semantic.working_state.page": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "semantic.working_state.refresh": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/memory-actions.mjs" },
  "source.declare": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/environment-actions.mjs" },
  "source.publish": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/source-policy-actions.mjs" },
  "source.revoke": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/environment-actions.mjs" },
  "tenant.get": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "tenant.list": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/identity-actions.mjs" },
  "workflow.bind": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "workflow.define": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "workflow.input.record": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/application-actions.mjs" },
  "workflow.patch.adopt": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "workflow.patch.propose": { state: "integrated", detail: "Authored Studio interaction", proof: "tests/studio/work-actions.mjs" },
  "case.recent": { state: "alternative", detail: "Start Center uses the authorized Case list; a separate recency section is not selected." },
  "cognitive.binding.set": { state: "integrated", detail: "Assign/replace an exact primary conversation target from authorized suitability evidence", proof: "tests/studio/conversation-actions.mjs" },
  "cognitive.plan": { state: "debt", detail: "Requires an exact integrity-qualified capability requirement. Studio does not fabricate owner digests; requirement preparation remains unconnected." },
  "events.resume": { state: "alternative", detail: "Host reconnection requests an authoritative snapshot; no claim that missed events were delivered." },
  "resource.attach": { state: "debt", detail: "Requires a native LocalAccessBinding/carrier plus access contract; authored secure Resource setup is not yet connected." },
  "runtime.readiness": { state: "alternative", detail: "Host telemetry reports actual scheduler supervision; runtime readiness is distinct from application health." },
  "semantic.ambient_refresh.assess": { state: "debt", detail: "Requires a real Conversation/Workflow consumer lineage. Generic inspection is not an ambient consumer." },
  "system.status": { state: "alternative", detail: "Desktop Host telemetry supplies current process/readiness facts; no duplicate status page." },
  "tenant.member.add": { state: "debt", detail: "Requires another enrolled exact Principal. Principal enrollment/discovery and multi-Principal interaction qualification remain open." },
};
export const studioOperationPosture = (id: string): StudioOperationPosture => studioOperationPostures[id] ?? { state: "debt", detail: "New Host operation: awaiting published-contract reconciliation and interaction qualification." };
