#pragma once

#ifndef INCLUDE_CONTAINER_CONTAINER_EVENT_H
#define INCLUDE_CONTAINER_CONTAINER_EVENT_H

enum yai_container_event_kind {
    YAI_CONTAINER_EVENT_UNKNOWN = 0,
    YAI_CONTAINER_EVENT_CREATE,
    YAI_CONTAINER_EVENT_START,
    YAI_CONTAINER_EVENT_STOP,
    YAI_CONTAINER_EVENT_RESTORE,
    YAI_CONTAINER_EVENT_DESTROY
};

#endif
