#pragma once

#ifndef INCLUDE_SUPERVISOR_SUPERVISOR_STATE_H
#define INCLUDE_SUPERVISOR_SUPERVISOR_STATE_H

enum yai_supervisor_state {
    YAI_SUPERVISOR_STATE_UNKNOWN = 0,
    YAI_SUPERVISOR_STATE_BOOTING,
    YAI_SUPERVISOR_STATE_READY,
    YAI_SUPERVISOR_STATE_MEDIATING,
    YAI_SUPERVISOR_STATE_DRAINING,
    YAI_SUPERVISOR_STATE_FAILED
};

#endif
