#pragma once

#ifndef INCLUDE_SUPERVISOR_SUPERVISOR_MODE_H
#define INCLUDE_SUPERVISOR_SUPERVISOR_MODE_H

enum yai_supervisor_mode {
    YAI_SUPERVISOR_MODE_PASSIVE = 0,
    YAI_SUPERVISOR_MODE_OBSERVE,
    YAI_SUPERVISOR_MODE_ENFORCE,
    YAI_SUPERVISOR_MODE_RECOVERY
};

#endif
