import { useState } from "react";
import { GraphViewport } from "../../live/GraphViewport";
import { Icon, type IconName } from "../../components/Icon";
import { Badge, Button, EmptyState, PanelHeader } from "../../components/primitives";
import type { CasePresentation } from "../../clients/dataSource";
import type { SurfaceInput } from "../../workbench/surface/model";
import type { AuxiliaryViewProps, SidebarViewProps, SurfaceRendererProps } from "../../workbench/kernel/types";
import { graphInput, materialInput, timelineInput } from "../surfaces/inputs";

export const perspectives = ["Overview", "Environment", "Knowledge", "Memory", "Authority", "Work", "Compute"] as const;
export type Perspective = typeof perspectives[number];

export const perspectiveMeta: Record<Perspective, { icon: IconName; meaning: string }> = {
  Overview: { icon: "overview", meaning: "Case identity and current posture" },
  Environment: { icon: "environment", meaning: "Sources, files and resources" },
  Knowledge: { icon: "knowledge", meaning: "Qualified source-grounded derivation" },
  Memory: { icon: "memory", meaning: "Committed history and derived relations" },
  Authority: { icon: "authority", meaning: "Policy, scope, review and decisions" },
  Work: { icon: "work", meaning: "Workflow definition and progression" },
  Compute: { icon: "compute", meaning: "Provider and runtime posture" },
};

export function CaseSidebarView({ workspace, containerId, selection, actions }: SidebarViewProps) {
  const perspective = containerId as Perspective;
  const rows = perspectiveRows(workspace, perspective);
  const openRow = (item: Row, pinned = false) => {
    if (item.surface) {
      actions.openSurface({ ...item.surface, id: pinned ? item.surface.identity : "surface:preview", pinned });
    } else if (item.material) {
      actions.openSurface(materialInput(workspace, item.id, item.label, pinned));
    } else {
      actions.inspect(item.id);
    }
  };
  return <div className="live-sidebar-content" data-view-container={containerId}>
    {perspective === "Overview" && <>
      <section className="sidebar-group"><h2>Case</h2><button title={workspace.case.case_ref} className={selection === workspace.case.case_ref ? "selected" : ""} onClick={() => actions.inspect(workspace.case.case_ref)}><Icon name="case" /><span><strong>{workspace.case.display_name}</strong><small>{workspace.case.case_ref}</small></span></button></section>
      <section className="sidebar-group case-outline"><h2>Perspectives</h2>{perspectives.slice(1).map((item) => <button key={item} onClick={() => actions.openPerspective(item)}><Icon name={perspectiveMeta[item].icon} /><span><strong>{item}</strong><small>{perspectiveMeta[item].meaning}</small></span></button>)}</section>
      <section className="sidebar-group"><h2>Participants <span>{workspace.overview.participants.length}</span></h2>{workspace.overview.participants.map((person) => <button key={person.id} className={selection === person.id ? "selected" : ""} onClick={() => actions.inspect(person.id)}><Icon name="people" /><span><strong>{person.id}</strong><small>{person.roles.join(", ") || "No role exposed"}</small></span>{person.is_current && <Badge tone="info">Current</Badge>}</button>)}</section>
    </>}
    {rows.map((group) => <section className="sidebar-group" key={group.label}><h2>{group.label}<span>{group.items.length}</span></h2>{group.items.map((item) => <button key={item.id} title={`${item.label} · ${item.detail}`} className={selection === item.id ? "selected" : ""} onClick={() => openRow(item)} onDoubleClick={() => (item.material || item.surface) && openRow(item, true)}><Icon name={item.icon} /><span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}{!group.items.length && <p className="sidebar-empty">No qualified items.</p>}</section>)}
  </div>;
}

export function PerspectiveSurface({ workspace, input, actions }: SurfaceRendererProps) {
  const perspective = (input.viewId ?? "Overview") as Perspective;
  if (perspective === "Overview") return <Overview workspace={workspace} inspect={actions.inspect} navigate={actions.openPerspective} />;
  if (perspective === "Environment") return <Environment workspace={workspace} inspect={actions.inspect} openSurface={actions.openSurface} />;
  if (perspective === "Knowledge") return <Knowledge workspace={workspace} inspect={actions.inspect} openSurface={actions.openSurface} />;
  if (perspective === "Memory") return <Memory workspace={workspace} openSurface={actions.openSurface} />;
  if (perspective === "Authority") return <Authority workspace={workspace} inspect={actions.inspect} />;
  if (perspective === "Work") return <Work workspace={workspace} inspect={actions.inspect} />;
  return <Compute workspace={workspace} inspect={actions.inspect} />;
}

export function TimelineSurface({ workspace, actions }: SurfaceRendererProps) {
  return <div className="live-page memory-page" data-surface-type="case.timeline"><SurfaceHeader workspace={workspace} title="Case Timeline" body="A temporal presentation of committed Case history. Chronology does not imply causality." /><ol className="real-timeline">{workspace.memory.timeline.slice().reverse().map((entry) => <li key={entry.id}><time>{formatTime(entry.committed_at_unix_ms)}</time><button onClick={() => actions.inspect(entry.id)}><i /><span><strong>{humanize(entry.kind)}</strong><small>{entry.component} · generation {entry.sequence}</small></span></button></li>)}</ol>{!workspace.memory.timeline.length && <EmptyState title="No committed activity" body="No history is exposed for the current Case projection." />}</div>;
}

export function GraphSurface({ workspace, input, actions }: SurfaceRendererProps) {
  const projection = input.metadata?.projection;
  const graph = projection === "knowledge" ? knowledgeGraph(workspace) : relationGraph(workspace);
  return <div className="live-page graph-surface" data-surface-type="case.graph"><SurfaceHeader workspace={workspace} title={input.title} body={projection === "knowledge" ? "Qualified source-grounded relations presented as a navigable graph." : "Derived Case relationships presented without becoming canonical truth."} />{graph.nodes.length ? <GraphViewport nodes={graph.nodes} edges={graph.edges} layout="relational" onInspect={actions.inspect} /> : <EmptyState title={`No ${input.title}`} body="No qualified relation projection is available for this Case." />}</div>;
}

export function SettingsSurface({ workspace, actions }: SurfaceRendererProps) {
  const sections = ["General", "Appearance", "YAI Host", "Workbench", "Terminal", "Providers"] as const;
  const [section, setSection] = useState<typeof sections[number]>("General");
  return <div className="settings-surface" data-surface-type="studio.settings"><aside><h1>Settings</h1>{sections.map((item) => <button key={item} aria-pressed={section === item} onClick={() => { setSection(item); actions.inspect(`settings:${item.toLowerCase()}`); }}>{item}</button>)}</aside><div className="settings-content"><span>Studio local preferences</span><h2>{section}</h2>{section === "General" && <section><h3>Case navigation</h3><p>Back and Forward traverse Studio UI history. Durable Case continuity remains in YAI.</p></section>}{section === "Appearance" && <section><h3>Interface foundation</h3><p>Studio uses shared Workbench typography, surfaces, controls and semantic tokens.</p></section>}{section === "YAI Host" && <section><h3>Backend posture</h3><dl><div><dt>Case data</dt><dd>{workspace.presentation.dataKind}</dd></div><div><dt>Backend</dt><dd>{workspace.presentation.backendPosture}</dd></div><div><dt>Generation</dt><dd>{workspace.case.generation}</dd></div></dl></section>}{section === "Terminal" && <section><h3>Integrated terminal</h3><p>PTY availability follows the desktop host, independently from Case data.</p></section>}</div></div>;
}

export function ConversationView({ workspace }: AuxiliaryViewProps) {
  return <div className="context-scroll"><PanelHeader title="Conversation" detail={workspace.conversation.read_only ? "Read only" : "Available"} />{workspace.conversation.turns.map((turn) => <article className="real-turn" key={turn.id}><header><strong>{turn.participant_ref}</strong><Badge>Generation {turn.generation}</Badge></header>{turn.parts.map((part, index) => <p key={index}>{part.text ?? `[${part.modality} · ${part.media_type}]`}</p>)}</article>)}{!workspace.conversation.turns.length && <EmptyState title="No committed turns" body="This Case has no conversation Turns visible to the current participant." />}<div className="read-only-draft"><textarea disabled placeholder="Send is not qualified" /><small>Studio will not fake-send.</small></div></div>;
}

export function ActivityView({ workspace, actions }: AuxiliaryViewProps) {
  return <div className="context-scroll"><PanelHeader title="Activity" detail={`Through generation ${workspace.case.generation}`} />{workspace.memory.timeline.slice(-20).reverse().map((entry) => <button className="context-event" key={entry.id} onClick={() => actions.inspect(entry.id)}><time>{formatTime(entry.committed_at_unix_ms)}</time><span><strong>{humanize(entry.kind)}</strong><small>{entry.component}</small></span></button>)}{!workspace.memory.timeline.length && <EmptyState title="No committed activity" body="No history is exposed for the current Case projection." />}</div>;
}

export function InspectorView({ workspace, selection, actions }: AuxiliaryViewProps) {
  const fact = findFact(workspace, selection);
  const kind = factKind(workspace, selection);
  const material = isMaterial(workspace, selection);
  const relations = workspace.memory.relations.filter((edge) => edge.from === selection || edge.to === selection).slice(0, 8);
  return <div className="context-scroll inspector"><PanelHeader title="Inspector" detail="Context in this Case" /><section className="inspector-hero"><div><Icon name={factIcon(kind)} size={18} /></div><span>{humanize(kind)}</span><h2>{fact.title}</h2><p>{fact.detail}</p>{material && <Button onClick={() => actions.openSurface(materialInput(workspace, selection, materialLabel(workspace, selection), true))}>Open in work surface</Button>}</section><section className="inspector-group"><h3>Properties</h3><dl>{fact.values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className="inspector-group"><h3>Case relationships <span>{relations.length}</span></h3>{relations.map((edge) => { const related = edge.from === selection ? edge.to : edge.from; return <button key={edge.id} onClick={() => actions.inspect(related)}><span>{edge.from === selection ? "To" : "From"}</span><strong>{compact(related)}</strong><small>{humanize(edge.kind)}</small></button>; })}{!relations.length && <p>No qualified graph relation is exposed for this fact.</p>}</section><footer>Inspector selection is local UI state. Case facts remain owned by YAI.</footer></div>;
}

function SurfaceHeader({ workspace, title, body }: { workspace: CasePresentation; title: string; body: string }) { return <header className="surface-title"><small>{workspace.case.case_ref} · Generation {workspace.case.generation}</small><h1>{title}</h1><p>{body}</p></header>; }
function Overview({ workspace, inspect, navigate }: { workspace: CasePresentation; inspect: (id: string) => void; navigate: (id: string) => void }) { return <div className="live-page case-overview"><SurfaceHeader workspace={workspace} title={workspace.case.display_name} body="The durable Case is the workspace: environment, knowledge, memory, authority, work and compute remain one continuity." /><section className="case-model"><div className="case-core" role="button" tabIndex={0} onClick={() => inspect(workspace.case.case_ref)}><Icon name="case" size={24} /><span>Case continuity</span><strong>{workspace.case.case_ref}</strong><dl><div><dt>Generation</dt><dd>{workspace.case.generation}</dd></div><div><dt>Lifecycle</dt><dd>{workspace.case.case_status}</dd></div><div><dt>Attached as</dt><dd>{workspace.case.participant_ref}</dd></div></dl></div><div className="case-dimensions">{perspectives.slice(1).map((item) => <button key={item} onClick={() => navigate(item)}><Icon name={perspectiveMeta[item].icon} size={18} /><span><strong>{item}</strong><small>{perspectiveMeta[item].meaning}</small></span><em>{dimensionDetail(workspace, item)}</em><Icon name="chevron" size={13} /></button>)}</div></section><section className="live-section"><PanelHeader title="Attention" detail="Consequences of current presentation facts" />{workspace.overview.attention.map((item) => <button className="fact-row" key={item.ref ?? item.title} onClick={() => inspect(item.ref ?? item.kind)}><Icon name={item.kind === "review" ? "review" : item.kind === "provider" ? "compute" : "work"} /><span><strong>{item.title}</strong><small>{item.detail}</small></span></button>)}{!workspace.overview.attention.length && <EmptyState title="No current attention" body="No pending review, unavailable provider or waiting workflow is exposed." />}</section></div>; }
function Environment({ workspace, inspect, openSurface }: { workspace: CasePresentation; inspect: (id: string) => void; openSurface: (input: SurfaceInput) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Environment" body="Sources, files and operational resources attached to this Case." /><FactSection title="Files" empty="No file inventory available">{workspace.environment.files.map((file) => <button className="fact-row" key={file.id} onClick={() => openSurface(materialInput(workspace, file.id, fileName(file.path)))} onDoubleClick={() => openSurface(materialInput(workspace, file.id, fileName(file.path), true))}><Icon name="sources" /><span><strong>{file.path}</strong><small>{file.source_label}</small></span></button>)}</FactSection><FactSection title="Sources" empty="No sources attached">{workspace.environment.sources.map((source) => <button className="fact-row" key={source.id} onClick={() => openSurface(materialInput(workspace, source.id, source.label))}><Icon name="sources" /><span><strong>{source.label}</strong><small>{source.perimeter}</small></span><Badge>{source.posture ?? "declared"}</Badge></button>)}</FactSection><FactSection title="Resources" empty="No resources attached">{workspace.environment.resources.map((resource) => <button className="fact-row" key={resource.id} onClick={() => inspect(resource.id)}><Icon name="environment" /><span><strong>{resource.id}</strong><small>{resource.kind}</small></span></button>)}</FactSection></div>; }
function Knowledge({ workspace, inspect, openSurface }: { workspace: CasePresentation; inspect: (id: string) => void; openSurface: (input: SurfaceInput) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Knowledge" body="Qualified, source-grounded derivations available to this Case." />{workspace.knowledge.status === "empty" ? <EmptyState title="No qualified Knowledge derivation" body={workspace.knowledge.message} /> : <><section className="surface-launch"><Icon name="graph" size={22} /><span><strong>Knowledge Graph</strong><small>{workspace.knowledge.relations.length} qualified relations</small></span><Button onClick={() => openSurface(graphInput("knowledge", true))}>Open graph</Button></section><FactSection title="Source-grounded units" empty="No units">{workspace.knowledge.units.map((unit) => <button className="fact-row" key={unit.id} onClick={() => inspect(unit.id)}><Icon name="knowledge" /><span><strong>{unit.entity_ref ?? humanize(unit.kind)}</strong><small>{unit.text}</small></span></button>)}</FactSection></>}</div>; }
function Memory({ workspace, openSurface }: { workspace: CasePresentation; openSurface: (input: SurfaceInput) => void }) { return <div className="live-page memory-page"><SurfaceHeader workspace={workspace} title="Memory" body="Committed history and derived relations are first-class Case surfaces." /><div className="surface-launch-grid"><button onClick={() => openSurface(timelineInput(true))}><Icon name="memory" size={22} /><span><strong>Case Timeline</strong><small>{workspace.memory.timeline.length} committed events</small></span></button><button onClick={() => openSurface(graphInput("memory", true))}><Icon name="graph" size={22} /><span><strong>Experience Graph</strong><small>{workspace.memory.relations.length} derived relations</small></span></button></div></div>; }
function Authority({ workspace, inspect }: { workspace: CasePresentation; inspect: (id: string) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Authority" body="Who may act, under which policy, review and decision facts." />{workspace.authority.empty ? <EmptyState title="No policy is bound to this Case" body="No policy, review or grant relationship is exposed." /> : <FactSection title="Reviews" empty="No reviews">{workspace.authority.reviews.map((review) => <button className="fact-row" key={review.id} onClick={() => inspect(review.id)}><Icon name="review" /><span><strong>{review.id}</strong><small>{review.operation_ref}</small></span><Badge>{review.status}</Badge></button>)}</FactSection>}</div>; }
function Work({ workspace, inspect }: { workspace: CasePresentation; inspect: (id: string) => void }) { const nodes = workspace.work.nodes.map((node) => ({ id: node.node_id, label: compact(node.node_id), kind: node.node_kind })); return <div className="live-page"><SurfaceHeader workspace={workspace} title="Work" body="Workflow definition and current progression remain distinct." />{workspace.work.status === "empty" ? <EmptyState title="No workflow is configured" body={workspace.work.message ?? "No workflow binding is exposed."} /> : <><GraphViewport nodes={nodes} edges={workspace.work.edges} layout="directed" onInspect={inspect} /><FactSection title="Current work" empty="No work nodes">{workspace.work.nodes.map((node) => <button className="fact-row" key={node.node_id} onClick={() => inspect(node.node_id)}><Icon name="work" /><span><strong>{node.node_id}</strong><small>{node.reason}</small></span><Badge>{node.posture}</Badge></button>)}</FactSection></>}</div>; }
function Compute({ workspace, inspect }: { workspace: CasePresentation; inspect: (id: string) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Compute" body="Generic provider targets and qualified runtime posture." /><FactSection title="Targets" empty={workspace.compute.message}>{workspace.compute.targets.map((target) => <button className="provider-row" key={target.id} onClick={() => inspect(target.id)}><Icon name="compute" /><span><strong>{target.provider_key}</strong><small>{target.adapter} · {target.model_id}</small></span><dl><dt>Locality</dt><dd>{target.locality}</dd><dt>Endpoint</dt><dd>{target.endpoint}</dd><dt>Management</dt><dd>{target.management}</dd></dl></button>)}</FactSection></div>; }
function FactSection({ title, empty, children }: { title: string; empty: string; children: React.ReactNode }) { const values = Array.isArray(children) ? children : [children]; return <section className="live-section"><PanelHeader title={title} />{values.length && values.some(Boolean) ? children : <EmptyState title={empty} body="Studio has not substituted authored product data." />}</section>; }

type Row = { id: string; label: string; detail: string; icon: IconName; material?: boolean; surface?: SurfaceInput };
function perspectiveRows(workspace: CasePresentation, perspective: Perspective): { label: string; items: Row[] }[] {
  if (perspective === "Environment") return [{ label: "Files", items: workspace.environment.files.map((item) => ({ id: item.id, label: fileName(item.path), detail: item.path, icon: "sources", material: true })) }, { label: "Sources", items: workspace.environment.sources.map((item) => ({ id: item.id, label: item.label, detail: `${item.media_type} · ${item.posture ?? "declared"}`, icon: "sources", material: true })) }, { label: "Resources", items: workspace.environment.resources.map((item) => ({ id: item.id, label: item.id, detail: item.kind, icon: "environment" })) }];
  if (perspective === "Knowledge") return [{ label: "Views", items: [{ id: "knowledge-graph", label: "Knowledge Graph", detail: `${workspace.knowledge.relations.length} relations`, icon: "graph", surface: graphInput("knowledge") }] }, { label: "Documents", items: workspace.knowledge.sources.map((item) => ({ id: item.id, label: item.label, detail: `${item.media_type} · ${item.path}`, icon: "sources", material: true })) }, { label: "Entities", items: workspace.knowledge.entities.map((item) => ({ id: item.id, label: compact(item.id), detail: `${item.definitions.length} definitions`, icon: "knowledge" })) }];
  if (perspective === "Memory") return [{ label: "Views", items: [{ id: "memory-timeline", label: "Case Timeline", detail: `${workspace.memory.timeline.length} events`, icon: "memory", surface: timelineInput() }, { id: "memory-graph", label: "Experience Graph", detail: `${workspace.memory.relations.length} relations`, icon: "graph", surface: graphInput("memory") }] }, { label: "History", items: workspace.memory.timeline.slice(-12).reverse().map((item) => ({ id: item.id, label: humanize(item.kind), detail: `Generation ${item.sequence}`, icon: "memory" })) }];
  if (perspective === "Authority") return [{ label: "Reviews", items: workspace.authority.reviews.map((item) => ({ id: item.id, label: compact(item.id), detail: item.status, icon: "review" })) }];
  if (perspective === "Work") return [{ label: "Workflow", items: workspace.work.nodes.map((item) => ({ id: item.node_id, label: compact(item.node_id), detail: item.posture, icon: "work" })) }];
  if (perspective === "Compute") return [{ label: "Targets", items: workspace.compute.targets.map((item) => ({ id: item.id, label: item.provider_key, detail: item.model_id, icon: "compute" })) }];
  return [];
}
function dimensionDetail(workspace: CasePresentation, perspective: Perspective) { if (perspective === "Environment") return `${workspace.environment.sources.length} sources · ${workspace.environment.resources.length} resources`; if (perspective === "Knowledge") return `${workspace.knowledge.units.length} units`; if (perspective === "Memory") return `${workspace.memory.timeline.length} events`; if (perspective === "Authority") return workspace.authority.empty ? "No bound facts" : `${workspace.authority.reviews.length} reviews`; if (perspective === "Work") return workspace.work.status; if (perspective === "Compute") return `${workspace.compute.targets.length} targets`; return ""; }
function relationGraph(workspace: CasePresentation) { const kinds = new Map<string, string>(); workspace.memory.relations.forEach((edge) => { kinds.set(edge.from, edge.from_kind ?? "fact"); kinds.set(edge.to, edge.to_kind ?? "fact"); }); return { nodes: [...kinds].map(([id, kind]) => ({ id, label: compact(id), kind })), edges: workspace.memory.relations }; }
function knowledgeGraph(workspace: CasePresentation) { return { nodes: workspace.knowledge.units.map((unit) => ({ id: unit.id, label: unit.entity_ref ?? compact(unit.id), kind: unit.kind })), edges: workspace.knowledge.relations }; }
function findFact(workspace: CasePresentation, id: string) { const values = (...rows: Array<[string, string]>): Array<[string, string]> => rows; if (id === workspace.case.case_ref) return { title: workspace.case.display_name, detail: "Durable continuity and application truth owned by YAI.", values: values(["Case", workspace.case.case_ref], ["Lifecycle", workspace.case.case_status], ["Generation", String(workspace.case.generation)], ["Attached participant", workspace.case.participant_ref], ["Data source", workspace.presentation.dataKind]) }; const fixture = workspace.presentation.materials?.find((item) => item.id === id); if (fixture) return { title: fixture.name, detail: fixture.provenance, values: values(["Media type", fixture.mediaType], ["Path", fixture.path], ["Representation", fixture.body.kind]) }; const file = workspace.environment.files.find((item) => item.id === id); if (file) return { title: fileName(file.path), detail: file.path, values: values(["Source", file.source_label], ["Revision", file.revision_ref], ["Digest", file.digest]) }; const source = workspace.environment.sources.find((item) => item.id === id); if (source) return { title: source.label, detail: source.perimeter, values: values(["Source", source.id], ["Media type", source.media_type], ["Posture", source.posture ?? "declared"]) }; const participant = workspace.overview.participants.find((item) => item.id === id); if (participant) return { title: participant.id, detail: participant.is_current ? "Current attached participant" : "Participant in this Case", values: values(["Roles", participant.roles.join(", ") || "Unavailable"]) }; const event = workspace.memory.timeline.find((item) => item.id === id); if (event) return { title: humanize(event.kind), detail: event.summary ?? "Committed Case transition", values: values(["Generation", String(event.sequence)], ["Owner", event.component]) }; const review = workspace.authority.reviews.find((item) => item.id === id); if (review) return { title: compact(review.id), detail: "Authority review bound to this Case.", values: values(["Status", review.status], ["Operation", review.operation_ref], ["Policy", review.policy_ref]) }; const provider = workspace.compute.targets.find((item) => item.id === id); if (provider) return { title: provider.provider_key, detail: provider.model_id, values: values(["Adapter", provider.adapter], ["Locality", provider.locality], ["Endpoint", provider.endpoint]) }; return { title: compact(id), detail: "Selected Case reference", values: values(["Reference", id], ["Case", workspace.case.case_ref]) }; }
function factKind(workspace: CasePresentation, id: string) { if (id === workspace.case.case_ref) return "case"; if (workspace.presentation.materials?.some((item) => item.id === id)) return "material"; if (workspace.environment.files.some((item) => item.id === id)) return "file"; if (workspace.environment.sources.some((item) => item.id === id)) return "source"; if (workspace.overview.participants.some((item) => item.id === id)) return "participant"; if (workspace.authority.reviews.some((item) => item.id === id)) return "review"; if (workspace.compute.targets.some((item) => item.id === id)) return "provider"; if (workspace.work.nodes.some((item) => item.node_id === id)) return "workflow"; if (workspace.memory.timeline.some((item) => item.id === id)) return "event"; return "case fact"; }
function factIcon(kind: string): IconName { return ({ case: "case", material: "file", file: "file", source: "sources", participant: "people", review: "review", provider: "compute", workflow: "work", event: "memory" } as Record<string, IconName>)[kind] ?? "overview"; }
function materialLabel(workspace: CasePresentation, id: string) { return workspace.presentation.materials?.find((item) => item.id === id)?.name ?? workspace.environment.files.find((item) => item.id === id)?.path.split("/").at(-1) ?? workspace.environment.sources.find((item) => item.id === id)?.label ?? compact(id); }
function isMaterial(workspace: CasePresentation, id: string) { return Boolean(workspace.presentation.materials?.some((item) => item.id === id) || workspace.environment.files.some((item) => item.id === id) || workspace.environment.sources.some((item) => item.id === id)); }
function compact(value: string) { return value.length > 38 ? `${value.slice(0, 20)}…${value.slice(-12)}` : value; }
function fileName(value: string) { return value.split(/[\\/]/).filter(Boolean).at(-1) ?? value; }
function humanize(value: string) { return value.replaceAll("_", " ").replace(/^./, (char) => char.toUpperCase()); }
function formatTime(value: number) { return new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit" }).format(value); }
