import { lazy } from "react";
import { Icon, type IconName } from "../../components/Icon";
import { Badge, Button, EmptyState, PanelHeader } from "../../components/primitives";
import type { CasePresentation } from "../../clients/dataSource";
import type { SurfaceInput } from "../../workbench/surface/model";
import type { AuxiliaryViewProps, SidebarViewProps, SurfaceRendererProps, SurfaceSearchResult } from "../../workbench/kernel/types";
import { fileIconForMedia, fileInput, graphInput, materialInput, resourceInput, sourceInput, timelineInput } from "../surfaces/inputs";
import { buildFileTree, type FileTreeNode } from "./environment";

const GraphViewport = lazy(() => import("../../live/GraphViewport").then((module) => ({ default: module.GraphViewport })));

export const perspectives = ["Overview", "Environment", "Knowledge", "Memory", "Authority", "Work", "Compute"] as const;
export type Perspective = typeof perspectives[number];

export const perspectiveMeta: Record<Perspective, { icon: IconName; meaning: string }> = {
  Overview: { icon: "overview", meaning: "Case identity and current posture" },
  Environment: { icon: "environment", meaning: "Sources, files and resources" },
  Knowledge: { icon: "knowledge", meaning: "Qualified source-grounded derivation" },
  Memory: { icon: "memory", meaning: "Committed history and derived relations" },
  Authority: { icon: "authority", meaning: "Policy, scope, review and decisions" },
  Work: { icon: "work", meaning: "Workflow definition and progression" },
  Compute: { icon: "compute", meaning: "Provider and runtime posture" },
};

export function CaseSidebarView({ workspace, containerId, selection, actions }: SidebarViewProps) {
  const perspective = containerId as Perspective;
  const rows = perspectiveRows(workspace, perspective);
  const openRow = (item: Row, pinned = false) => {
    if (item.surface) {
      actions.openSurface({ ...item.surface, id: pinned ? item.surface.identity : "surface:preview", pinned });
    } else if (item.material) {
      actions.openSurface(materialInput(workspace, item.id, item.label, pinned));
    } else {
      actions.inspect(item.id);
    }
  };
  return <div className="live-sidebar-content" data-view-container={containerId}>
    {perspective === "Overview" && <>
      <section className="sidebar-group"><h2>Case</h2><button title={workspace.case.case_ref} className={selection === workspace.case.case_ref ? "selected" : ""} onClick={() => actions.inspect(workspace.case.case_ref)}><Icon name="case" /><span><strong>{workspace.case.display_name}</strong><small>{workspace.case.case_ref}</small></span></button></section>
      <section className="sidebar-group case-outline"><h2>Perspectives</h2>{perspectives.slice(1).map((item) => <button key={item} onClick={() => actions.openPerspective(item)}><Icon name={perspectiveMeta[item].icon} /><span><strong>{item}</strong><small>{perspectiveMeta[item].meaning}</small></span></button>)}</section>
      <section className="sidebar-group"><h2>Participants <span>{workspace.overview.participants.length}</span></h2>{workspace.overview.participants.map((person) => <button key={person.id} className={selection === person.id ? "selected" : ""} onClick={() => actions.inspect(person.id)}><Icon name="people" /><span><strong>{person.id}</strong><small>{person.roles.join(", ") || "No role exposed"}</small></span>{person.is_current && <Badge tone="info">Current</Badge>}</button>)}</section>
    </>}
    {perspective === "Environment" && <EnvironmentExplorer workspace={workspace} selection={selection} open={actions.openSurface} inspect={actions.inspect} />}
    {perspective !== "Environment" && rows.map((group) => <section className="sidebar-group" key={group.label}><h2>{group.label}<span>{group.items.length}</span></h2>{group.items.map((item) => <button key={item.id} title={`${item.label} · ${item.detail}`} className={selection === item.id ? "selected" : ""} onClick={() => openRow(item)} onDoubleClick={() => (item.material || item.surface) && openRow(item, true)}><Icon name={item.icon} /><span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}{!group.items.length && <p className="sidebar-empty">No qualified items.</p>}</section>)}
  </div>;
}

function EnvironmentExplorer({ workspace, selection, open, inspect }: { workspace: CasePresentation; selection: string; open: (input: SurfaceInput) => void; inspect: (id: string) => void }) {
  return <>
    <section className="sidebar-group environment-files"><h2>Files <span>{workspace.environment.files.length}</span></h2><FileTree nodes={buildFileTree(workspace.environment.files)} workspace={workspace} selection={selection} open={open} inspect={inspect} depth={0} /></section>
    <section className="sidebar-group"><h2>Sources <span>{workspace.environment.sources.length}</span></h2>{workspace.environment.sources.map((source) => <button key={source.id} className={selection === source.id ? "selected" : ""} onClick={() => { inspect(source.id); open(sourceInput(workspace, source.id)); }} onDoubleClick={() => open(sourceInput(workspace, source.id, true))}><Icon name="source" /><span><strong>{source.label}</strong><small>{humanize(source.kind)} · {source.posture ?? "declared"}</small></span></button>)}</section>
    <section className="sidebar-group"><h2>Resources <span>{workspace.environment.resources.length}</span></h2>{workspace.environment.resources.map((resource) => <button key={resource.id} className={selection === resource.id ? "selected" : ""} onClick={() => { inspect(resource.id); open(resourceInput(workspace, resource.id)); }} onDoubleClick={() => open(resourceInput(workspace, resource.id, true))}><Icon name={resource.kind === "database" ? "database" : "resource"} /><span><strong>{resource.label ?? resourceLabel(resource.id)}</strong><small>{humanize(resource.kind)}</small></span></button>)}</section>
  </>;
}

function FileTree({ nodes, workspace, selection, open, inspect, depth }: { nodes: FileTreeNode[]; workspace: CasePresentation; selection: string; open: (input: SurfaceInput) => void; inspect: (id: string) => void; depth: number }) {
  return <div className="file-tree">{nodes.map((node) => node.fileId ? <button key={node.path} style={{ paddingLeft: `${8 + depth * 14}px` }} className={selection === node.fileId ? "selected" : ""} title={node.path} onClick={() => { inspect(node.fileId!); open(fileInput(workspace, node.fileId!)); }} onDoubleClick={() => open(fileInput(workspace, node.fileId!, true))}><Icon name={fileIconForMedia(workspace.environment.files.find((file) => file.id === node.fileId)?.media_type, node.path)} /><span><strong>{node.name}</strong></span></button> : <details key={node.path} open><summary style={{ paddingLeft: `${6 + depth * 14}px` }}><Icon name="environment" /><strong>{node.name}</strong></summary><FileTree nodes={node.children} workspace={workspace} selection={selection} open={open} inspect={inspect} depth={depth + 1} /></details>)}</div>;
}

export function PerspectiveSurface({ workspace, input, actions }: SurfaceRendererProps) {
  const perspective = (input.viewId ?? "Overview") as Perspective;
  if (perspective === "Overview") return <Overview workspace={workspace} inspect={actions.inspect} navigate={actions.openPerspective} />;
  if (perspective === "Environment") return <Environment workspace={workspace} inspect={actions.inspect} openSurface={actions.openSurface} />;
  if (perspective === "Knowledge") return <Knowledge workspace={workspace} inspect={actions.inspect} openSurface={actions.openSurface} />;
  if (perspective === "Memory") return <Memory workspace={workspace} openSurface={actions.openSurface} />;
  if (perspective === "Authority") return <Authority workspace={workspace} inspect={actions.inspect} />;
  if (perspective === "Work") return <Work workspace={workspace} inspect={actions.inspect} />;
  return <Compute workspace={workspace} inspect={actions.inspect} />;
}

export function TimelineSurface({ workspace, actions }: SurfaceRendererProps) {
  return <div className="live-page memory-page" data-surface-type="case.timeline"><SurfaceHeader workspace={workspace} title="Case Timeline" body="A temporal presentation of committed Case history. Chronology does not imply causality." /><ol className="real-timeline">{workspace.memory.timeline.slice().reverse().map((entry) => <li key={entry.id}><time>{formatTime(entry.committed_at_unix_ms)}</time><button onClick={() => actions.inspect(entry.id)}><i /><span><strong>{humanize(entry.kind)}</strong><small>{entry.component} · generation {entry.sequence}</small></span></button></li>)}</ol>{!workspace.memory.timeline.length && <EmptyState title="No committed activity" body="No history is exposed for the current Case projection." />}</div>;
}

export function GraphSurface({ workspace, input, actions }: SurfaceRendererProps) {
  const projection = input.metadata?.projection;
  const graph = projection === "knowledge" ? knowledgeGraph(workspace) : relationGraph(workspace);
  return <div className="live-page graph-surface" data-surface-type="case.graph"><SurfaceHeader workspace={workspace} title={input.title} body={projection === "knowledge" ? "Qualified source-grounded relations presented as a navigable graph." : "Derived Case relationships presented without becoming canonical truth."} />{graph.nodes.length ? <GraphViewport nodes={graph.nodes} edges={graph.edges} layout="relational" onInspect={actions.inspect} /> : <EmptyState title={`No ${input.title}`} body="No qualified relation projection is available for this Case." />}</div>;
}

export function SourceSurface({ workspace, input, actions }: SurfaceRendererProps) {
  const source = workspace.environment.sources.find((item) => item.id === input.objectRef);
  if (!source) return <EmptyState title="Source unavailable" body="This Source is not present in the current Case projection." />;
  const files = workspace.environment.files.filter((file) => file.source_ref === source.id);
  const resource = workspace.environment.resources.find((item) => item.id === source.resource_ref);
  return <article className="live-page object-surface source-surface" data-surface-type="environment.source"><SurfaceHeader workspace={workspace} title={source.label} body="A governed Case Source relationship. Its retained material is navigated separately." /><dl className="object-facts"><div><dt>Kind</dt><dd>{humanize(source.kind)}</dd></div><div><dt>Posture</dt><dd>{source.posture ?? "declared"}</dd></div><div><dt>Roles</dt><dd>{source.roles.join(", ")}</dd></div><div><dt>Perimeter</dt><dd>{source.perimeter}</dd></div><div><dt>Resource</dt><dd><button onClick={() => actions.openSurface(resourceInput(workspace, source.resource_ref))}>{resource?.label ?? resourceLabel(source.resource_ref)}</button></dd></div><div><dt>Revision</dt><dd>{source.revision_ref ?? "Not acquired"}</dd></div></dl><FactSection title="Retained material" empty="No acquired material">{files.map((file) => <button className="fact-row" key={file.id} onClick={() => actions.openSurface(fileInput(workspace, file.id))}><Icon name={fileIconForMedia(file.media_type, file.path)} /><span><strong>{fileName(file.path)}</strong><small>{file.path}</small></span></button>)}</FactSection><p className="surface-note">Knowledge may derive from this Source, but remains a rebuildable projection rather than the Source itself.</p></article>;
}

export function ResourceSurface({ workspace, input, actions }: SurfaceRendererProps) {
  const resource = workspace.environment.resources.find((item) => item.id === input.objectRef);
  if (!resource) return <EmptyState title="Resource unavailable" body="This Resource is not present in the current Case projection." />;
  const sources = workspace.environment.sources.filter((source) => source.resource_ref === resource.id);
  return <article className="live-page object-surface resource-surface" data-surface-type="environment.resource"><SurfaceHeader workspace={workspace} title={resource.label ?? resourceLabel(resource.id)} body={`${humanize(resource.kind)} capability attached to this Case.`} /><dl className="object-facts"><div><dt>Kind</dt><dd>{humanize(resource.kind)}</dd></div><div><dt>Review</dt><dd>{humanize(resource.review_requirement)}</dd></div><div><dt>Policy</dt><dd>{resource.policy_ref}</dd></div><div><dt>Operations</dt><dd>{resource.operations.length ? resource.operations.join(", ") : "No disclosed operations"}</dd></div>{resource.read_prefixes.length > 0 && <div><dt>Read scope</dt><dd>{resource.read_prefixes.join(", ")}</dd></div>}{resource.allowed_write_prefix && <div><dt>Write scope</dt><dd>{resource.allowed_write_prefix}</dd></div>}</dl><FactSection title="Related Sources" empty="No related Sources">{sources.map((source) => <button className="fact-row" key={source.id} onClick={() => actions.openSurface(sourceInput(workspace, source.id))}><Icon name="source" /><span><strong>{source.label}</strong><small>{humanize(source.kind)} · {source.posture ?? "declared"}</small></span></button>)}</FactSection></article>;
}

export function searchTimelineSurface({ workspace }: Pick<SurfaceRendererProps, "workspace">, _input: SurfaceRendererProps["input"], query: string): readonly SurfaceSearchResult[] {
  const needle = query.trim().toLocaleLowerCase();
  if (!needle) return [];
  return workspace.memory.timeline
    .filter((entry) => `${entry.kind} ${entry.component} ${entry.summary ?? ""} ${entry.sequence}`.toLocaleLowerCase().includes(needle))
    .map((entry) => ({ id: entry.id, label: humanize(entry.kind), detail: `${entry.component} · generation ${entry.sequence}`, objectRef: entry.id }));
}

export function searchGraphSurface({ workspace }: Pick<SurfaceRendererProps, "workspace">, input: SurfaceRendererProps["input"], query: string): readonly SurfaceSearchResult[] {
  const needle = query.trim().toLocaleLowerCase();
  if (!needle) return [];
  const graph = input.metadata?.projection === "knowledge" ? knowledgeGraph(workspace) : relationGraph(workspace);
  return graph.nodes
    .filter((node) => `${node.label} ${node.id} ${node.kind}`.toLocaleLowerCase().includes(needle))
    .map((node) => ({ id: node.id, label: node.label, detail: humanize(node.kind), objectRef: node.id }));
}

export function ConversationView({ workspace }: AuxiliaryViewProps) {
  return <div className="context-scroll conversation-view"><PanelHeader title="Conversation" detail={workspace.conversation.read_only ? "Committed turns · read only" : "Available"} />{workspace.conversation.turns.map((turn) => { const participant = workspace.overview.participants.find((item) => item.id === turn.participant_ref); const tone = participant?.roles.some((role) => /assistant|ai|model/i.test(role)) ? "ai" : turn.participant_ref.startsWith("yai") ? "system" : "human"; return <article className={`real-turn turn-${tone}`} key={turn.id}><header><span className="turn-avatar">{turn.participant_ref.slice(0, 2).toUpperCase()}</span><strong>{turn.participant_ref}</strong><Badge>Generation {turn.generation}</Badge></header>{turn.parts.map((part, index) => <p key={index}>{part.text ?? `[${part.modality} · ${part.media_type}]`}</p>)}</article>; })}{!workspace.conversation.turns.length && <EmptyState title="No committed turns" body="This Case has no conversation Turns visible to the current participant." />}<div className="read-only-draft"><textarea disabled placeholder="Send is not qualified" aria-label="Conversation draft unavailable" /><small>Conversation is part of this Case. Sending is not qualified at this boundary.</small></div></div>;
}

export function ActivityView({ workspace, actions }: AuxiliaryViewProps) {
  return <div className="context-scroll activity-view"><PanelHeader title="Activity" detail={`Through generation ${workspace.case.generation}`} />{workspace.memory.timeline.slice(-20).reverse().map((entry) => <button className={`context-event event-${activityTone(entry.kind)}`} key={entry.id} onClick={() => actions.inspect(entry.id)}><time>{formatTime(entry.committed_at_unix_ms)}</time><i /><span><strong>{humanize(entry.kind)}</strong><small>{entry.component} · generation {entry.sequence}</small></span></button>)}{!workspace.memory.timeline.length && <EmptyState title="No committed activity" body="No history is exposed for the current Case projection." />}</div>;
}

export function InspectorView({ workspace, selection, actions }: AuxiliaryViewProps) {
  const fact = findFact(workspace, selection);
  const kind = factKind(workspace, selection);
  const material = isMaterial(workspace, selection);
  const relations = workspace.memory.relations.filter((edge) => edge.from === selection || edge.to === selection).slice(0, 8);
  const openMaterial = () => actions.openSurface(workspace.environment.files.some((file) => file.id === selection)
    ? fileInput(workspace, selection, true)
    : materialInput(workspace, selection, materialLabel(workspace, selection), true));
  return <div className="context-scroll inspector"><PanelHeader title="Inspector" detail="Context in this Case" /><section className="inspector-hero"><div><Icon name={factIcon(kind)} size={18} /></div><span>{humanize(kind)}</span><h2>{fact.title}</h2><p>{fact.detail}</p>{material && <Button onClick={openMaterial}>Open file</Button>}{kind === "source" && <Button onClick={() => actions.openSurface(sourceInput(workspace, selection, true))}>Open Source</Button>}{kind === "resource" && <Button onClick={() => actions.openSurface(resourceInput(workspace, selection, true))}>Open Resource</Button>}</section><section className="inspector-group"><h3>Case relationships <span>{relations.length}</span></h3>{relations.map((edge) => { const related = edge.from === selection ? edge.to : edge.from; return <button key={edge.id} onClick={() => actions.inspect(related)}><span>{edge.from === selection ? "→" : "←"}</span><strong>{compact(related)}</strong><small>{humanize(edge.kind)} · {edge.from === selection ? "outgoing" : "incoming"}</small></button>; })}{!relations.length && <p>No qualified graph relation is exposed for this fact.</p>}</section><details className="inspector-technical"><summary>Technical details</summary><dl>{fact.values.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></details><footer>Inspector selection is local UI state. Case facts remain owned by YAI.</footer></div>;
}

function SurfaceHeader({ workspace, title, body }: { workspace: CasePresentation; title: string; body: string }) { return <header className="surface-title"><small title={workspace.case.case_ref}>{workspace.case.display_name} · Generation {workspace.case.generation}</small><h1>{title}</h1><p>{body}</p></header>; }
function Overview({ workspace, inspect, navigate }: { workspace: CasePresentation; inspect: (id: string) => void; navigate: (id: string) => void }) { return <div className="live-page case-overview"><SurfaceHeader workspace={workspace} title={workspace.case.display_name} body="The durable Case is the workspace: environment, knowledge, memory, authority, work and compute remain one continuity." /><section className="case-model"><div className="case-core" role="button" tabIndex={0} title={workspace.case.case_ref} onClick={() => inspect(workspace.case.case_ref)}><Icon name="case" size={24} /><span>Case continuity</span><strong>{workspace.case.display_name}</strong><dl><div><dt>Generation</dt><dd>{workspace.case.generation}</dd></div><div><dt>Lifecycle</dt><dd>{workspace.case.case_status}</dd></div><div><dt>Attached as</dt><dd>{workspace.case.participant_ref}</dd></div></dl></div><div className="case-dimensions">{perspectives.slice(1).map((item) => <button key={item} onClick={() => navigate(item)}><Icon name={perspectiveMeta[item].icon} size={18} /><span><strong>{item}</strong><small>{perspectiveMeta[item].meaning}</small></span><em>{dimensionDetail(workspace, item)}</em><Icon name="chevron" size={13} /></button>)}</div></section><section className="live-section"><PanelHeader title="Attention" detail="Consequences of current presentation facts" />{workspace.overview.attention.map((item) => <button className="fact-row" key={item.ref ?? item.title} onClick={() => inspect(item.ref ?? item.kind)}><Icon name={item.kind === "review" ? "review" : item.kind === "provider" ? "compute" : "work"} /><span><strong>{item.title}</strong><small>{item.detail}</small></span></button>)}{!workspace.overview.attention.length && <EmptyState title="No current attention" body="No pending review, unavailable provider or waiting workflow is exposed." />}</section></div>; }
function Environment({ workspace, openSurface }: { workspace: CasePresentation; inspect: (id: string) => void; openSurface: (input: SurfaceInput) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Environment" body="The files available to this Case, the governed Sources that define its information perimeter, and the Resources through which it can operate." /><section className="environment-summary"><button onClick={() => workspace.environment.files[0] && openSurface(fileInput(workspace, workspace.environment.files[0].id))}><Icon name="file" size={22} /><strong>{workspace.environment.files.length}</strong><span>Files</span></button><button onClick={() => workspace.environment.sources[0] && openSurface(sourceInput(workspace, workspace.environment.sources[0].id))}><Icon name="sources" size={22} /><strong>{workspace.environment.sources.length}</strong><span>Sources</span></button><button onClick={() => workspace.environment.resources[0] && openSurface(resourceInput(workspace, workspace.environment.resources[0].id))}><Icon name="environment" size={22} /><strong>{workspace.environment.resources.length}</strong><span>Resources</span></button></section><FactSection title="Information perimeter" empty="No Sources attached">{workspace.environment.sources.map((source) => <button className="fact-row" key={source.id} onClick={() => openSurface(sourceInput(workspace, source.id))}><Icon name="source" /><span><strong>{source.label}</strong><small>{humanize(source.kind)} · {source.perimeter}</small></span><Badge>{source.posture ?? "declared"}</Badge></button>)}</FactSection></div>; }
function Knowledge({ workspace, inspect, openSurface }: { workspace: CasePresentation; inspect: (id: string) => void; openSurface: (input: SurfaceInput) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Knowledge" body="Qualified, source-grounded derivations available to this Case." />{workspace.knowledge.status === "empty" ? <EmptyState title="No qualified Knowledge derivation" body={workspace.knowledge.message} /> : <><section className="surface-launch"><Icon name="graph" size={22} /><span><strong>Knowledge Graph</strong><small>{workspace.knowledge.relations.length} qualified relations</small></span><Button onClick={() => openSurface(graphInput("knowledge", true))}>Open graph</Button></section><FactSection title="Source-grounded units" empty="No units">{workspace.knowledge.units.map((unit) => <button className="fact-row" key={unit.id} onClick={() => inspect(unit.id)}><Icon name="knowledge" /><span><strong>{unit.entity_ref ?? humanize(unit.kind)}</strong><small>{unit.text}</small></span></button>)}</FactSection></>}</div>; }
function Memory({ workspace, openSurface }: { workspace: CasePresentation; openSurface: (input: SurfaceInput) => void }) { return <div className="live-page memory-page"><SurfaceHeader workspace={workspace} title="Memory" body="Committed history and derived relations are first-class Case surfaces." /><div className="surface-launch-grid"><button onClick={() => openSurface(timelineInput(true))}><Icon name="memory" size={22} /><span><strong>Case Timeline</strong><small>{workspace.memory.timeline.length} committed events</small></span></button><button onClick={() => openSurface(graphInput("memory", true))}><Icon name="graph" size={22} /><span><strong>Experience Graph</strong><small>{workspace.memory.relations.length} derived relations</small></span></button></div></div>; }
function Authority({ workspace, inspect }: { workspace: CasePresentation; inspect: (id: string) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Authority" body="Who may act, under which policy, review and decision facts." />{workspace.authority.empty ? <EmptyState title="No policy is bound to this Case" body="No policy, review or grant relationship is exposed." /> : <><FactSection title="Bound policies" empty="No policy bindings">{workspace.authority.policies.map((policy) => <button className="fact-row" key={policy.id} onClick={() => inspect(policy.id)}><Icon name="authority" /><span><strong>{humanize(policy.policy_key)}</strong><small>{policy.owner_ref} · version {policy.version}</small></span><Badge tone="success">Bound</Badge></button>)}</FactSection><FactSection title="Reviews" empty="No pending reviews">{workspace.authority.reviews.map((review) => <button className="fact-row" key={review.id} onClick={() => inspect(review.id)}><Icon name="review" /><span><strong>{review.id}</strong><small>{review.operation_ref}</small></span><Badge>{review.status}</Badge></button>)}</FactSection></>}</div>; }
function Work({ workspace, inspect }: { workspace: CasePresentation; inspect: (id: string) => void }) { const nodes = workspace.work.nodes.map((node) => ({ id: node.node_id, label: compact(node.node_id), kind: node.node_kind })); return <div className="live-page"><SurfaceHeader workspace={workspace} title="Work" body="Workflow definition and current progression remain distinct." />{workspace.work.status === "empty" ? <EmptyState title="No workflow is configured" body={workspace.work.message ?? "No workflow binding is exposed."} /> : <><GraphViewport nodes={nodes} edges={workspace.work.edges} layout="directed" onInspect={inspect} /><FactSection title="Current work" empty="No work nodes">{workspace.work.nodes.map((node) => <button className="fact-row" key={node.node_id} onClick={() => inspect(node.node_id)}><Icon name="work" /><span><strong>{node.node_id}</strong><small>{node.reason}</small></span><Badge>{node.posture}</Badge></button>)}</FactSection></>}</div>; }
function Compute({ workspace, inspect }: { workspace: CasePresentation; inspect: (id: string) => void }) { return <div className="live-page"><SurfaceHeader workspace={workspace} title="Compute" body="Models run through governed provider/runtime targets; deployment identity and health remain distinct from model identity." /><FactSection title="Targets / deployments" empty={workspace.compute.message}>{workspace.compute.targets.map((target) => <button className="provider-row" key={target.id} onClick={() => inspect(target.id)}><Icon name="compute" /><span><strong>{target.provider_key}</strong><small>Model {target.model_id} · runtime adapter {target.adapter}</small></span><dl><dt>Locality</dt><dd>{target.locality}</dd><dt>Endpoint</dt><dd>{target.endpoint}</dd><dt>Management</dt><dd>{target.management}</dd></dl></button>)}</FactSection>{!workspace.compute.targets.length && <p className="surface-note">No model, provider/runtime or target/deployment is bound to this Case. YVEX management is a separate future control plane.</p>}</div>; }
function FactSection({ title, empty, children }: { title: string; empty: string; children: React.ReactNode }) { const values = Array.isArray(children) ? children : [children]; return <section className="live-section"><PanelHeader title={title} />{values.length && values.some(Boolean) ? children : <EmptyState title={empty} body="Studio has not substituted authored product data." />}</section>; }

type Row = { id: string; label: string; detail: string; icon: IconName; material?: boolean; surface?: SurfaceInput };
function perspectiveRows(workspace: CasePresentation, perspective: Perspective): { label: string; items: Row[] }[] {
  // Environment owns a typed explorer rather than flattening Files, Sources and
  // Resources into the generic material-row path.
  if (perspective === "Environment") return [];
  if (perspective === "Knowledge") return [{ label: "Views", items: [{ id: "knowledge-graph", label: "Knowledge Graph", detail: `${workspace.knowledge.relations.length} relations`, icon: "graph", surface: graphInput("knowledge") }] }, { label: "Documents", items: workspace.knowledge.sources.map((item) => ({ id: item.id, label: item.label, detail: `${item.media_type} · ${item.path}`, icon: "sources", material: true })) }, { label: "Entities", items: workspace.knowledge.entities.map((item) => ({ id: item.id, label: compact(item.id), detail: `${item.definitions.length} definitions`, icon: "knowledge" })) }];
  if (perspective === "Memory") return [{ label: "Views", items: [{ id: "memory-timeline", label: "Case Timeline", detail: `${workspace.memory.timeline.length} events`, icon: "memory", surface: timelineInput() }, { id: "memory-graph", label: "Experience Graph", detail: `${workspace.memory.relations.length} relations`, icon: "graph", surface: graphInput("memory") }] }, { label: "History", items: workspace.memory.timeline.slice(-12).reverse().map((item) => ({ id: item.id, label: humanize(item.kind), detail: `Generation ${item.sequence}`, icon: "memory" })) }];
  if (perspective === "Authority") return [{ label: "Policies", items: workspace.authority.policies.map((item) => ({ id: item.id, label: humanize(item.policy_key), detail: `version ${item.version} · bound`, icon: "authority" })) }, { label: "Reviews", items: workspace.authority.reviews.map((item) => ({ id: item.id, label: compact(item.id), detail: item.status, icon: "review" })) }];
  if (perspective === "Work") return [{ label: "Workflow", items: workspace.work.nodes.map((item) => ({ id: item.node_id, label: compact(item.node_id), detail: item.posture, icon: "work" })) }];
  if (perspective === "Compute") return [{ label: "Targets", items: workspace.compute.targets.map((item) => ({ id: item.id, label: item.provider_key, detail: item.model_id, icon: "compute" })) }];
  return [];
}
function dimensionDetail(workspace: CasePresentation, perspective: Perspective) { if (perspective === "Environment") return `${workspace.environment.sources.length} sources · ${workspace.environment.resources.length} resources`; if (perspective === "Knowledge") return `${workspace.knowledge.units.length} units`; if (perspective === "Memory") return `${workspace.memory.timeline.length} events`; if (perspective === "Authority") return workspace.authority.empty ? "No bound facts" : `${workspace.authority.policies.length} policies · ${workspace.authority.reviews.length} reviews`; if (perspective === "Work") return workspace.work.status; if (perspective === "Compute") return `${workspace.compute.targets.length} targets`; return ""; }
function relationGraph(workspace: CasePresentation) { const kinds = new Map<string, string>(); workspace.memory.relations.forEach((edge) => { kinds.set(edge.from, edge.from_kind ?? "fact"); kinds.set(edge.to, edge.to_kind ?? "fact"); }); return { nodes: [...kinds].map(([id, kind]) => ({ id, label: compact(id), kind })), edges: workspace.memory.relations }; }
function knowledgeGraph(workspace: CasePresentation) { return { nodes: workspace.knowledge.units.map((unit) => ({ id: unit.id, label: unit.entity_ref ?? compact(unit.id), kind: unit.kind })), edges: workspace.knowledge.relations }; }
function findFact(workspace: CasePresentation, id: string) {
  const values = (...rows: Array<[string, string]>): Array<[string, string]> => rows;
  if (id === workspace.case.case_ref) return { title: workspace.case.display_name, detail: "Durable continuity and application truth owned by YAI.", values: values(["Case", workspace.case.case_ref], ["Lifecycle", workspace.case.case_status], ["Generation", String(workspace.case.generation)], ["Attached participant", workspace.case.participant_ref], ["Data source", workspace.presentation.dataKind]) };
  const fixture = workspace.presentation.materials?.find((item) => item.id === id); if (fixture) return { title: fixture.name, detail: fixture.provenance, values: values(["Media type", fixture.mediaType], ["Path", fixture.path], ["Representation", fixture.body.kind]) };
  const file = workspace.environment.files.find((item) => item.id === id); if (file) { const source = workspace.environment.sources.find((item) => item.id === file.source_ref); return { title: fileName(file.path), detail: file.path, values: values(["Object", file.id], ["Path", file.path], ["Source", file.source_ref], ["Resource", source?.resource_ref ?? "Not exposed"], ["Revision", file.revision_ref], ["Digest", file.digest], ["Size", `${file.bytes} bytes`], ["Media type", file.media_type], ["Backing", typeof file.backing === "string" ? file.backing : JSON.stringify(file.backing)], ["Case generation", String(workspace.case.generation)], ["Mutation", "Unavailable — no admitted participant-origin file write"]) }; }
  const source = workspace.environment.sources.find((item) => item.id === id); if (source) return { title: source.label, detail: source.perimeter, values: values(["Source", source.id], ["Kind", source.kind], ["Roles", source.roles.join(", ")], ["Resource", source.resource_ref], ["Revision", source.revision_ref ?? "Not acquired"], ["Media type", source.media_type], ["Posture", source.posture ?? "declared"]) };
  const resource = workspace.environment.resources.find((item) => item.id === id); if (resource) return { title: resource.label ?? resourceLabel(resource.id), detail: "Operational capability attached to this Case.", values: values(["Resource", resource.id], ["Kind", resource.kind], ["Policy", resource.policy_ref], ["Review", resource.review_requirement], ["Operations", resource.operations.join(", ") || "None disclosed"], ["Read scope", resource.read_prefixes.join(", ") || "None disclosed"]) };
  const participant = workspace.overview.participants.find((item) => item.id === id); if (participant) return { title: participant.id, detail: participant.is_current ? "Current attached participant" : "Participant in this Case", values: values(["Roles", participant.roles.join(", ") || "Unavailable"]) };
  const policy = workspace.authority.policies.find((item) => item.id === id); if (policy) return { title: humanize(policy.policy_key), detail: policy.reason, values: values(["Binding", policy.id], ["Owner", policy.owner_ref], ["Version", policy.version], ["Source", policy.source_ref], ["Artifact", policy.artifact_ref]) };
  const event = workspace.memory.timeline.find((item) => item.id === id); if (event) return { title: humanize(event.kind), detail: event.summary ?? "Committed Case transition", values: values(["Generation", String(event.sequence)], ["Owner", event.component]) };
  const review = workspace.authority.reviews.find((item) => item.id === id); if (review) return { title: compact(review.id), detail: "Authority review bound to this Case.", values: values(["Status", review.status], ["Operation", review.operation_ref], ["Policy", review.policy_ref]) };
  const provider = workspace.compute.targets.find((item) => item.id === id); if (provider) return { title: provider.provider_key, detail: provider.model_id, values: values(["Adapter", provider.adapter], ["Locality", provider.locality], ["Endpoint", provider.endpoint]) };
  return { title: compact(id), detail: "Selected Case reference", values: values(["Reference", id], ["Case", workspace.case.case_ref]) };
}
function factKind(workspace: CasePresentation, id: string) { if (id === workspace.case.case_ref) return "case"; if (workspace.presentation.materials?.some((item) => item.id === id)) return "material"; if (workspace.environment.files.some((item) => item.id === id)) return "file"; if (workspace.environment.sources.some((item) => item.id === id)) return "source"; if (workspace.environment.resources.some((item) => item.id === id)) return "resource"; if (workspace.overview.participants.some((item) => item.id === id)) return "participant"; if (workspace.authority.policies.some((item) => item.id === id)) return "policy"; if (workspace.authority.reviews.some((item) => item.id === id)) return "review"; if (workspace.compute.targets.some((item) => item.id === id)) return "provider"; if (workspace.work.nodes.some((item) => item.node_id === id)) return "workflow"; if (workspace.memory.timeline.some((item) => item.id === id)) return "event"; return "case fact"; }
function factIcon(kind: string): IconName { return ({ case: "case", material: "file", file: "file", source: "source", resource: "resource", participant: "people", policy: "authority", review: "review", provider: "compute", workflow: "work", event: "memory" } as Record<string, IconName>)[kind] ?? "overview"; }
function materialLabel(workspace: CasePresentation, id: string) { return workspace.presentation.materials?.find((item) => item.id === id)?.name ?? workspace.environment.files.find((item) => item.id === id)?.path.split("/").at(-1) ?? compact(id); }
function isMaterial(workspace: CasePresentation, id: string) { return Boolean(workspace.presentation.materials?.some((item) => item.id === id) || workspace.environment.files.some((item) => item.id === id)); }
function compact(value: string) { return value.length > 38 ? `${value.slice(0, 20)}…${value.slice(-12)}` : value; }
function fileName(value: string) { return value.split(/[\\/]/).filter(Boolean).at(-1) ?? value; }
function resourceLabel(value: string) { return value.replace(/^resource:/, "").replaceAll("-", " ").replace(/^./, (char) => char.toUpperCase()); }
function humanize(value: string) { return value.replaceAll("_", " ").replace(/^./, (char) => char.toUpperCase()); }
function formatTime(value: number) { return new Intl.DateTimeFormat(undefined, { hour: "2-digit", minute: "2-digit" }).format(value); }
function activityTone(value: string) { if (/fail|deny|revoke/i.test(value)) return "error"; if (/review|wait|request/i.test(value)) return "warning"; if (/complete|commit|create|admit/i.test(value)) return "success"; return "info"; }
