import { factKind } from "./facts";
import { DecisionFrontier } from "./DecisionFrontier";
import { useRef, useState } from "react";
import type { SurfaceRendererProps } from "../../workbench/kernel/types";
import type { OperationResult } from "../../clients/live";
import { defaultRecallBounds, type RecallRequest, type RecallResult, type RecalledEvidence, type WorkingState, type WorkingStateResult } from "../../clients/memory";
import { ApplicationActionDialog } from "../../components/ApplicationActionDialog";
import { Badge, Button, EmptyState, PanelHeader } from "../../components/primitives";
import { useApplicationAvailability } from "./applicationActions";

const human = (value: string) => value.replaceAll("_", " ");
const refs = (value: FormDataEntryValue | null) => String(value ?? "").split(/\r?\n/).map(item => item.trim()).filter(Boolean);

export function RecallSurface({ workspace, platform, actions }: SurfaceRendererProps) {
  useApplicationAvailability(platform.application);
  const [open, setOpen] = useState(false);
  const [result, setResult] = useState<RecallResult>();
  const application = platform.application;
  const trace = result?.trace.request.case_id === workspace.case.case_ref ? result.trace : undefined;
  return <article className="live-page memory-operational" data-surface-type="memory.recall"><header className="surface-title"><small>{workspace.case.display_name}</small><h1>Recall</h1><p>Documentary evidence, historical experience and current anchors qualified for an explicit task and cut.</p></header><Button disabled={!application?.supports("semantic.recall")} onClick={() => setOpen(true)}>Recall for a task</Button>
    {trace ? <><PanelHeader title={trace.request.query} detail={`Cut ${trace.request.at.value} · observed generation ${trace.generation}`} actions={<Badge tone={trace.request.expected_generation === workspace.case.generation ? "info" : "warning"}>{trace.request.expected_generation === workspace.case.generation ? "Captured result" : "Case changed"}</Badge>} /><Evidence workspace={workspace} evidence={trace} inspect={actions.inspect} /><Qualification complete={trace.closure_complete} omitted={trace.omitted_candidates} limitations={trace.limitations} /><details><summary>Exact trace identity</summary><code>{trace.trace_id}</code></details></> : <EmptyState title="No Recall requested" body={application?.supports("semantic.recall") ? "Choose a task, an exact generation and any required references. Recall does not execute a model or change the Case." : "The connected Host does not expose qualified Recall here."} />}
    {open && application && <TaskDialog title="Recall for a task" workspace={workspace} close={() => setOpen(false)} submit={async request => { const response = await application.recall(request); if (response.result_state === "success" && response.data) setResult(response.data); return response; }} />}
  </article>;
}

export function WorkingStateSurface({ workspace, platform, actions }: SurfaceRendererProps) {
  useApplicationAvailability(platform.application);
  const application = platform.application;
  const [open, setOpen] = useState(false);
  const [admit, setAdmit] = useState(false);
  const [result, setResult] = useState<WorkingStateResult>();
  const [error, setError] = useState<string>();
  const [busy, setBusy] = useState(false);
  const running = useRef(false);
  const state = result?.working_state.case_id === workspace.case.case_ref ? result.working_state : undefined;
  const update = async (action: () => Promise<OperationResult<WorkingStateResult>>) => {
    if (running.current) return; running.current = true; setBusy(true); setError(undefined);
    try { const response = await action(); if (response.result_state === "success" && response.data) setResult(response.data); else setError(response.error?.safe_message ?? response.result_state); }
    finally { running.current = false; setBusy(false); }
  };
  const page = (state: WorkingState, reference: string, resident: boolean) => update(() => application!.pageWorkingState(state, { schema: "yai.semantic_page_request.v1", case_id: state.case_id, participant_id: state.participant_id, base_working_state_id: state.working_state_id, references: [reference], action: resident ? "page_out" : "page_in", bounds: defaultRecallBounds }));
  return <article className="live-page memory-operational" data-surface-type="memory.working-state"><header className="surface-title"><small>{workspace.case.display_name}</small><h1>Working State</h1><p>Task-local compilation of current control and qualified evidence. Derived, bounded and disposable.</p></header>
    <div className="object-action-row"><Button disabled={!application?.supports("semantic.working_state.compile") || busy} onClick={() => setOpen(true)}>Compile Working State</Button><Button disabled={!state || !application?.supports("semantic.working_state.refresh") || busy} onClick={() => state && void update(() => application!.refreshWorkingState(state, { schema: "yai.working_refresh_request.v1", case_id: state.case_id, participant_id: state.participant_id, base_working_state_id: state.working_state_id, budget: null }))}>Refresh exact task</Button><Button disabled={!application?.supports("participant.view.admit") || busy} onClick={() => setAdmit(true)}>Admit model-context view…</Button></div>
    {error && <p className="policy-refusal" role="alert">{error} The previous result remains a captured snapshot; it is not newly qualified.</p>}
    {state ? <><PanelHeader title={state.request.intent} detail={`Generation ${state.case_generation} · ${state.bounds.selected_items} items · ${state.bounds.selected_semantic_units} semantic units`} actions={<Badge tone={state.case_generation === workspace.case.generation ? "info" : "warning"}>{state.case_generation === workspace.case.generation ? "Captured result" : "Refresh required"}</Badge>} />
      <section><h2>Current state and required control</h2>{state.entries.filter(entry => !["recalled_evidence", "semantic_page_references", "recall_qualification"].includes(entry.value.kind)).map(entry => <details className="working-entry" key={entry.entry_id}><summary>{human(entry.value.kind)} <Badge>{entry.posture}</Badge></summary><dl className="object-facts">{Object.entries(entry.value.value).filter(([, value]) => value == null || typeof value !== "object" || Array.isArray(value) && value.every(item => typeof item === "string")).map(([key, value]) => <div key={key}><dt>{human(key)}</dt><dd>{Array.isArray(value) ? value.join(", ") : String(value ?? "Not provided")}</dd></div>)}</dl><details><summary>Exact qualified structure</summary><pre>{JSON.stringify(entry.value.value, null, 2)}</pre></details><small>{entry.provenance.map(item => item.source_ref).join(" · ")}</small></details>)}</section>
      {state.entries.filter(entry => entry.value.kind === "recalled_evidence" && entry.value.value.evidence).map(entry => <Evidence workspace={workspace} key={entry.entry_id} evidence={entry.value.value.evidence!} inspect={actions.inspect} />)}
      {state.entries.filter(entry => entry.value.kind === "semantic_page_references").map(entry => <section key={entry.entry_id}><h2>W4 evidence groups</h2><p>Expand an exact deferred group explicitly. Paging checks current disclosure and backing; a reference grants no authority.</p>{entry.value.value.references?.map(reference => { const resident = entry.value.value.resident_references?.includes(reference.reference_id) ?? false; return <div className="working-reference" key={reference.reference_id}><div><strong>{reference.family}</strong><small>{reference.sources.map(source => source.path).join(", ") || `${reference.members.length} exact members`}</small><Badge tone={resident ? "info" : "neutral"}>{resident ? "Resident" : "Deferred"}</Badge>{reference.mandatory_task_dependency && <Badge tone="warning">Required</Badge>}</div><Button disabled={busy || !application?.supports("semantic.working_state.page") || state.case_generation !== workspace.case.generation || resident && reference.mandatory_task_dependency} onClick={() => void page(state, reference.reference_id, resident)}>{resident ? "Defer group" : "Expand group"}</Button></div>; })}</section>)}
      <Qualification complete={state.recall?.recall_closure_complete ?? false} omitted={state.bounds.omitted_items} limitations={state.recall?.limitations ?? []} /><p className="surface-note">Budget omissions: {state.bounds.omitted_by_budget} · locality omissions: {state.bounds.omitted_by_locality}. Automatic refresh is unavailable here: the current assessment contract requires a real Conversation/Workflow consumer lineage.</p><details><summary>Working State identity</summary><code>{state.working_state_id}</code></details><DecisionFrontier busy={busy} key={state.working_state_id} state={state} currentGeneration={workspace.case.generation} application={application} />
    </> : <EmptyState title="No Working State compiled" body="Choose a task to compile a bounded view. YAI requires the current Participant’s admitted model-context view; Studio does not grant it implicitly." />}
    {open && application && <TaskDialog title="Compile Working State" workspace={workspace} close={() => setOpen(false)} submit={async request => {
      const response = await application.compileWorkingState({ case_id: request.case_id, expected_generation: request.expected_generation, compilation: { scope: { participant_id: request.participant_id, purpose: "inspection", consumer: "model", view_kind: "model_context", max_items: 48, max_provider_claims: 6, max_interaction_turns: 8 }, intent: request.query, output_contract_id: "studio.semantic-inspection.v1", max_semantic_units: 16384, max_derived_items: 48, resource_refs: [], required_refs: request.required_refs, previous_item_ids: [], view_selection_id: null }, at: request.at, recall_required_refs: request.required_refs, recall_bounds: request.bounds, max_output_bytes: 1048576 }, true);
      if (response.result_state === "success" && response.data) { setResult(response.data); setError(undefined); } return response;
    }} />}
    {admit && application && <ApplicationActionDialog title="Admit model-context view" description="Explicitly admit the model/model_context view for the current Case Participant. This is a canonical YAI operation, checked against your current authority. It neither invokes a model nor permits external effects." submitLabel="Admit view" close={() => setAdmit(false)} submit={() => application.admitParticipantView({ case_ref: workspace.case.case_ref, participant_ref: workspace.case.participant_ref, consumer: "model", view_kind: "model_context" })} committed={() => platform.commands.executeCommand("studio.case.refresh").then(() => undefined)}><p>{workspace.case.participant_ref}</p></ApplicationActionDialog>}
  </article>;
}

function TaskDialog({ title, workspace, close, submit }: { title: string; workspace: SurfaceRendererProps["workspace"]; close(): void; submit(request: RecallRequest): Promise<OperationResult<unknown>> }) {
  const [generation] = useState(workspace.case.generation);
  return <ApplicationActionDialog title={title} description="Select an exact historical cut within the current Case. YAI still applies current disclosure and validates required references." submitLabel={title.startsWith("Recall") ? "Run Recall" : "Compile"} close={close} enabled={generation === workspace.case.generation} committed={() => undefined} submit={form => submit({ schema: "yai.recall_request.v2", case_id: workspace.case.case_ref, expected_generation: generation, participant_id: workspace.case.participant_ref, at: { kind: "generation", value: Number(form.get("cut")) }, query: String(form.get("task")).trim(), required_refs: refs(form.get("refs")), bounds: { ...defaultRecallBounds, candidates: Number(form.get("candidates")) } })}>
    <label>Task / query<textarea name="task" required autoFocus rows={3} maxLength={2048} /></label><label>Exact generation<input name="cut" type="number" min={0} max={generation} defaultValue={generation} required /></label><label>Candidate bound<input name="candidates" type="number" min={1} max={256} defaultValue={16} required /></label><label>Required references, one per line<textarea name="refs" rows={3} placeholder="Optional exact references; missing or hidden references are refused." /></label><small>Captured generation {generation}. Ranking is relevance, not confidence or truth. Working State uses a 48-item / 16,384-unit budget with explicit paging.</small>{generation !== workspace.case.generation && <p role="alert">The Case changed. Reopen this action to use its current generation.</p>}
  </ApplicationActionDialog>;
}

function Evidence({ evidence, inspect, workspace }: { workspace: SurfaceRendererProps["workspace"]; evidence: RecalledEvidence; inspect(id: string): void }) {
  return <div className="recall-evidence"><section><PanelHeader title="Documentary evidence" detail={`${evidence.documentary?.units.length ?? 0} units`} />{evidence.documentary?.units.map(item => <article className="recall-item" key={item.unit.id}><header><Badge>{human(item.unit.posture)}</Badge><Button disabled={factKind(workspace, item.unit.id) === "case fact"} title={factKind(workspace, item.unit.id) === "case fact" ? "This exact historical unit is not in the current Inspector projection; its retained text and reference are shown here." : undefined} onClick={() => inspect(item.unit.id)}>Inspect unit</Button></header><p>{item.unit.text}</p><small>Selected: {item.reasons.map(human).join(", ")}</small><details><summary>Exact reference</summary><code>{item.unit.id}</code></details></article>)}{!evidence.documentary?.units.length && <p>No documentary unit selected.</p>}</section><section><PanelHeader title="Historical experience" detail={`${evidence.events.length} events`} />{evidence.events.map(item => <button className="recall-event" disabled={!workspace.memory.timeline.some(event => event.id === item.event.transition_id)} title={item.event.transition_id} key={item.event.transition_id} onClick={() => inspect(item.event.transition_id)}><strong>{item.label}</strong><span>{human(item.validity_at_cut)}</span><small>Selected: {item.reasons.map(human).join(", ")}</small></button>)}{!evidence.events.length && <p>No historical event selected.</p>}</section><details><summary>Source closure · {evidence.closure_complete ? "complete" : "incomplete"}</summary><ul>{evidence.source_closure.map((item, i) => <li key={i}><code>{item.source_ref}</code> · {item.posture}</li>)}</ul></details></div>;
}

function Qualification({ complete, omitted, limitations }: { complete: boolean; omitted: number; limitations: string[] }) {
  return <section className="memory-qualification"><Badge tone={complete ? "success" : "warning"}>Closure {complete ? "complete" : "incomplete"}</Badge><span>{omitted} omitted</span>{limitations.length > 0 && <ul>{limitations.map((item, i) => <li key={i}>{item}</li>)}</ul>}<p>Complete source closure does not establish task sufficiency. Derived evidence is not operational authority.</p></section>;
}
