#pragma once

#ifndef INCLUDE_NET_PEER_STATE_H
#define INCLUDE_NET_PEER_STATE_H

enum yai_net_peer_state {
    YAI_NET_PEER_STATE_UNKNOWN = 0,
    YAI_NET_PEER_STATE_DISCOVERED,
    YAI_NET_PEER_STATE_ENROLLED,
    YAI_NET_PEER_STATE_ACTIVE,
    YAI_NET_PEER_STATE_ISOLATED
};

#endif
