#pragma once

#ifndef INCLUDE_NET_PLANE_STATE_H
#define INCLUDE_NET_PLANE_STATE_H

enum yai_net_plane_state {
    YAI_NET_PLANE_STATE_UNKNOWN = 0,
    YAI_NET_PLANE_STATE_INIT,
    YAI_NET_PLANE_STATE_READY,
    YAI_NET_PLANE_STATE_DEGRADED,
    YAI_NET_PLANE_STATE_FAILED
};

#endif
