#pragma once

#ifndef INCLUDE_IPC_ADMISSION_H
#define INCLUDE_IPC_ADMISSION_H

enum yai_ipc_admission_result {
    YAI_IPC_ADMISSION_UNKNOWN = 0,
    YAI_IPC_ADMISSION_ALLOW,
    YAI_IPC_ADMISSION_DENY,
    YAI_IPC_ADMISSION_DEFER
};

#endif
