#pragma once

#ifndef INCLUDE_IPC_CHANNEL_STATE_H
#define INCLUDE_IPC_CHANNEL_STATE_H

enum yai_ipc_channel_state {
    YAI_IPC_CHANNEL_UNKNOWN = 0,
    YAI_IPC_CHANNEL_OPEN,
    YAI_IPC_CHANNEL_READY,
    YAI_IPC_CHANNEL_DRAINING,
    YAI_IPC_CHANNEL_CLOSED
};

#endif
