#pragma once

#ifndef INCLUDE_CONTAINER_CONTAINER_STATE_H
#define INCLUDE_CONTAINER_CONTAINER_STATE_H

enum yai_container_state {
    YAI_CONTAINER_STATE_UNKNOWN = 0,
    YAI_CONTAINER_STATE_CREATED,
    YAI_CONTAINER_STATE_STARTING,
    YAI_CONTAINER_STATE_RUNNING,
    YAI_CONTAINER_STATE_STOPPED,
    YAI_CONTAINER_STATE_FAILED
};

#endif
