#pragma once

#ifndef INCLUDE_CONTAINER_CONTAINER_MODE_H
#define INCLUDE_CONTAINER_CONTAINER_MODE_H

enum yai_container_mode {
    YAI_CONTAINER_MODE_NONE = 0,
    YAI_CONTAINER_MODE_EPHEMERAL,
    YAI_CONTAINER_MODE_PERSISTENT,
    YAI_CONTAINER_MODE_RECOVERY,
    YAI_CONTAINER_MODE_PRIVILEGED
};

#endif
